### ISSUE TITLE
Call to undefined method App\Models\User::getInvoiceInformation()

### ISSUE THREAD

**Issue by Jacobtims** [mollie/laravel-cashier-mollie#104]
Hello,

When I try to download a invoice I get the following error:
`Call to undefined method App\Models\User::getInvoiceInformation()`
(Stack trace: https://flareapp.io/share/W7zV4R27#F54)

Code for downloading invoice:
```
Route::get('/download-invoice/{orderId}', function ($orderId) {
   return (request()->user()->downloadInvoice($orderId));
});
```

I have included the `Laravel\Cashier\Billable` trait in my User model.
I hope someone can help me with this.

Best regards,
Jacob

**Comment by sandervanhooft** [comment]
Hi @Jacobtims,

Can you double check that you have followed the installation guide?

https://www.cashiermollie.com/01-installation.html#setup

**Comment by Jacobtims** [comment]
Yes, I just did it again and it's still gives me the same error

**Comment by ciungulete** [comment]
Hi @Jacobtims! 
You add this 👇 in the billable model?
```php
/**
* Get the receiver information for the invoice.
* Typically includes the name and some sort of (E-mail/physical) address.
*
* @return array An array of strings
*/
public function getInvoiceInformation()
{
    return [$this->name, $this->email];
}
```

**Comment by Jacobtims** [comment]
Wow, that was the problem.
Thx! 👍
