### ISSUE TITLE
User is redirected to payment page if amount is zero and I get charged by Mollie for a 0€ payment, is this normal behaviour ?

### ISSUE THREAD

**Issue by WhereIsLucas** [mollie/laravel-cashier-mollie#107]
Hi, 

Thanks for this package! 

I'm giving 100% discount codes for some of my users so they can get free access to the subscription part of my app, but they are redirected to the payment page and they have to add a card, which I want to avoid if possible.

Moreover, I'm charged by Mollie for the 0€ transaction which is quite annoying for me.

Is this normal/wanted behaviour ? Is there any other way to circumvent this ?

Thanks for your help !

**Comment by sandervanhooft** [comment]
Hi @WhereIsLucas ,

Free subscriptions are not supported by Cashier Mollie and should be handled outside the package.

Some pointers to handle your use case:

- handle the free subscription coupons using your own logic, pass cashier coupons on to cashier.
- apply a [generic trial](https://www.cashiermollie.com/03-trials.html#without-mandate-upfront) with an end date far far away if you want to use Cashier

**Comment by WhereIsLucas** [comment]
Alright, thanks for your answer.
I'll follow the pointers you mentionned.
