### ISSUE TITLE
 Argument 1 passed to mollie_object_to_money() must be an object, null given, 

### ISSUE THREAD

**Issue by jasimjuwel** [mollie/laravel-cashier-mollie#108]
TypeError 
  Argument 1 passed to mollie_object_to_money() must be an object, null given, called in /vendor/mollie/laravel-cashier mollie/src/Mollie/GetMollieMethodMaximumAmount.php on line 17

at vendor/mollie/laravel-cashier-mollie/src/Helpers/helpers.php:94

**Getting this error when runnign cashier:run command in php 7.4, Laravel 8 and Mollie version 2.4.2**

**Comment by sandervanhooft** [comment]
Hi @jasimjuwel ,

Thanks for reporting this.

Can you share the order items (db rows) that are not getting processed? Please redact them if there's any sensitive data.

cc @ciungulete

**Comment by jasimjuwel** [comment]
Hi sandervanhooft,
I have added the rows of order items table,

`(1, '2022-06-30 06:38:49', 'Laravel\\Cashier\\Subscription', 1, 'App\\User', 132, '1 Monatew Laufzeit', '[\"From 2024-08-27 to 2024-09-27\"]', 'EUR', 1, 2490, 0.0000, 72, '2022-05-17 06:38:49', '2022-08-01 15:03:46'),`

**Comment by sandervanhooft** [comment]
Thanks!

1. Are there any Mollie related exceptions in your log?

1. If available, can you share the full exception trace, i.e. through Laravel Flare?

**Comment by ciungulete** [comment]
Thanks @jasim-cierra for details. I fix it in https://github.com/mollie/laravel-cashier-mollie/pull/110. For some payment methods, like PayPal, Mollie don't have a maximum amount.

Ping @sandervanhooft

**Comment by sandervanhooft** [comment]
Thanks @ciungulete @jasimjuwel @jasim-cierra !

I've just released the patch.
