### ISSUE TITLE
Hosted Checkout Testing without prefilled values

### ISSUE THREAD

**Issue by Master-Minder** [mollie/laravel-cashier-mollie#115]
With the current checkout implementation in test mode there is no way to fill in actual data e.g. credit card or bank details, but everything come prefilled. This should be definatly an available feature, to test the checkout flow in different scenarios like timed out 3DS, typos in bank details and similar user errors.
For propper testing before going live this is a must have feature.

**Comment by sandervanhooft** [comment]
Hi @Master-Minder ,

Thanks for your input. This is however not a feature of this package; Mollie takes care of all of this in their hosted checkout. From there, the payment either succeeds, fails or gets cancelled. The customer then gets redirected back to the redirectUrl provided by Cashier.
