### ISSUE TITLE
Canceling Subscription endsAt must be type \Carbon\Carbon, null given

### ISSUE THREAD

**Issue by RemiHin** [mollie/laravel-cashier-mollie#116]
Hi,

When i cancel my subscription
```$subscription->cancel()```

i get the following error:
```
TypeError
Laravel\Cashier\Subscription::cancelAt(): Argument #1 ($endsAt) must be of type Carbon\Carbon, null given, called in /vendor/mollie/laravel-cashier-mollie/src/Subscription.php on line 270
```

I don't do trials, and my cycle_ends_at is filled.
```
>>> $subscription->cycle_ends_at
=> Illuminate\Support\Carbon @1663320047 {#4336
     date: 2022-09-16 11:20:47.0 Europe/Amsterdam (+02:00),
}
```

Strangest thing is, despite the error, the subscription is canceled as it should be.

Any clue on if im doing something wrong? Or is this a bug?

**Comment by RemiHin** [comment]
Somehow Flare gave the wrong error.
Turns out that the next actions that was performed (sending an email confirming the cancellation) errored out because of missing env variables. Flare just said "here is where it went wrong" and pointed to cashier. But thats not where it went wrong.

**Comment by sandervanhooft** [comment]
Thank you for clearing that up @RemiHin !

Enjoy!
