### ISSUE TITLE
Not possible to create One-time Charges according to Mollie support

### ISSUE THREAD

**Issue by Master-Minder** [mollie/laravel-cashier-mollie#117]
It seems in your code there is no functionallity to create a one-time charge. According to Mollie support where I raised the issue already, the call mentioned in the documentation to Laravel\Cashier\Charge::newCharge() is only resulting in First Payments and Reccurring Payments not in One Off Payments. Which makes it impossible to access payment methods like bank transfer, which are only available as a one off payment, but not as a first or reccuring one.

**Comment by divdax** [comment]
Also tried to setup a one time charge: https://www.cashiermollie.com/04-charges.html
My user model has the Laravel\Cashier\Billable trait but when i try to charge the user i get the error `Call to undefined method App\Models\User::newCharge()`

**Comment by sandervanhooft** [comment]
Hi @Master-Minder ,

That's correct. Cashier is designed to leverage Mollie's recurring payment methods only. I'll add a note to the docs to clarify this.

**Comment by sandervanhooft** [comment]
@Master-Minder also note that it's possible to directly create a bank transfer mandate using Mollie's Mandate API and then use that with this package to trigger the charge / start a subscription etc.

**Comment by sandervanhooft** [comment]
See #92 for example
