### ISSUE TITLE
Wrong documentation for refunds

### ISSUE THREAD

**Issue by Master-Minder** [mollie/laravel-cashier-mollie#118]
In the documentation the call for refunds is mentioned as follows:

$shippingCosts = RefundItem::make([
    'owner' => $user,
    'description' => 'Shipping costs',
    'currency' => 'EUR',
    'quantity' => 1,
    'unit_price' => '6.67',
    'tax_percentage' => 21,
]);

While according to the code the make call requieres 'owner_id' and 'owner_type' and that the 'unit_price' get's typcasted to an int which will fail if you pass a string as mentioned in the documentation.

The call after that makes it even more wrong and will allways fail for orders with just 1 item.

$order->newRefund()
    ->addItem(RefundItem::MakeFromOrderItem($order->items->first()))
    ->addItem($shippingCosts)
    ->create();
    
Here you add the first order item with a full refund and try to add a 2nd item which results in an attempt to refund more than the order total. For orders with more than one item, it will create the refund, if you use the adjusted code I mentioned before, but will fail on the API processRefund call with the error Call to a member function handlePaymentRefunded() on null vendor/mollie/laravel-cashier-mollie/src/Refunds/Refund.php:91 which is obvious, since the 2nd RefundItem is not linked to any order item.

Correctly the call should be as follows:
$order->newRefund()
    ->addItem(RefundItem::MakeFromOrderItem($payment->order->items->first(), [
		'description'             => 'Refund reason here',
		'unit_price'              => $unitPriceAsInt,
	]))->create();

**Comment by sandervanhooft** [comment]
Hi @Master-Minder ,

Thanks for bringing this to my attention.

> While according to the code the make call requieres 'owner_id' and 'owner_type' and that the 'unit_price' get's typcasted to an int which will fail if you pass a string as mentioned in the documentation.

Agree on the string being incorrect in this example, fixing that.

> The call after that makes it even more wrong and will allways fail for orders with just 1 item.

Not sure what you mean here. Can you elaborate a bit?

> Here you add the first order item with a full refund and try to add a 2nd item which results in an attempt to refund more than the order total.

Mollie allows refund amounts to be slightly higher than the original order amount. A typical use case here would be covering the return shipping costs.

> For orders with more than one item, it will create the refund, if you use the adjusted code I mentioned before, but will fail on the API processRefund call with the error Call to a member function handlePaymentRefunded() on null vendor/mollie/laravel-cashier-mollie/src/Refunds/Refund.php:91 which is obvious, since the 2nd RefundItem is not linked to any order item.

Fixed, will be included on next release
