### ISSUE TITLE
One-Time charge: order items orderable_id / model

### ISSUE THREAD

**Issue by divdax** [mollie/laravel-cashier-mollie#122]
It would be great we could set the `orderable` morph relationship for one time charges like so:

```php
$product = App\Models\SomethingOrderable::find(1);
$result = $user->newCharge();

$item = new ChargeItemBuilder($user);
$item->quantity($data->qty);
$item->unitPrice(money($data->price*100,'EUR'));
$item->description($data->name);
$item->taxPercentage(19);
$tiem->orderableModel($product); // <---------- new method

$result->addItem($item->make());

$result = $result->create();
```

Currently `orderable_id` & `oderable_type` in table `order_items` is always empty.

**Comment by sandervanhooft** [comment]
How about this?

```php
$item = new \Laravel\Cashier\Charge\ChargeItemBuilder($user, $orderable);
```

**Comment by divdax** [comment]
@sandervanhooft yeah... much better! :)

**Comment by sandervanhooft** [comment]
Would be even cooler to do something like this and fill everything automatically:

```php
class ChargeItemBuilder
{
    // ...

    public static function forChargeable(Chargeable $chargeable, Model $billable)
    {
        
        $result = new static($billable);
        $result->orderable = $chargeable->orderable();
        $result->unitPrice($chargeable->unitPrice());
        $result->description($chargeable->description());
        $result->taxPercentage($billable->taxPercentage());

        return $result;
    }
}
```

```php
interface Chargeable
{
    public function orderable(): Model;
    public function unitPrice(): Money;
    public function description(): string;
}
```

This would require some additional modifications around handlePaymentFailed/Paid on the orderable model (also see `InteractsWithOrderItems`. 🤔

Need to investigate if this is possible without breaking change.

**Comment by sandervanhooft** [comment]
For clarity, this would allow you to do stuff like

```php
$itemA = ChargeItemBuilder::forChargeable($chargeableA, $billable)->make();
$itemB = ChargeItemBuilder::forChargeable($chargeableB, $billable)
    ->taxPercentage(5.5) // overrides allowed
    ->description('Some other description')  // overrides allowed
    ->quantity(3)
    ->make();

$result = $user->newCharge()
    ->addItem($itemA)
    ->addItem($itemB)
    ->setRedirectUrl('https://www.example.com')
    ->create();
```

**Comment by divdax** [comment]
This is awesome! 😍

**Comment by sandervanhooft** [comment]
Thanks @divdax .

This is going to involve several steps, need to be careful to not break any existing installations. First impressions:

1. Add `InteractsWithOrderItems` into the following interfaces and apply as such:
    - `HandlesPaymentStatusUpdates`
    - `ProcessesOrderItem`
    - `PreprocessesOrderItems` (already exists)

1. Add checks to `Order.handlePaymentPaid` etc to check if the `handlePaymentFailed` method exists on the item before calling it.

1. Add `Chargeable` interface.

1. Add `ChargeItemBuilder::forChargeable()`

**Comment by divdax** [comment]
Do you think it's possible?

**Comment by sandervanhooft** [comment]
We have put the first steps towards this on our backlog 🤞

**Comment by tobischulz** [comment]
Hey, this would help a lot! 
Is there currently any way to get all one-time charges for a user?

**Comment by valerius21** [comment]
Any updates on this?

**Comment by Naoray** [comment]
Hi @valerius21,

this will likely included within the next major release of this package. There is currently no ETA for the next major release, but I expect it to happen within this year.
