### ISSUE TITLE
Possible to install next to cashier stripe?

### ISSUE THREAD

**Issue by sitenzo** [mollie/laravel-cashier-mollie#124]
Hi All,

Is it possible to install this extension in a application where cashier stripe is already installed?
I want to make a base portal where i can choose the payment system (Mollie or Stripe) in the .env

Is this possible, because the both use billable and some other same class names.

Thanks for the response.

**Comment by sandervanhooft** [comment]
Hi,

This is not possible, this package was designed as a replacement for other cashier packages.
