### ISSUE TITLE
No means yes when using cashier:install

### ISSUE THREAD

**Issue by mano-gilissen** [mollie/laravel-cashier-mollie#129]
Hello,

When trying to install this package i got stuck for hours on the php artisan cashier:install command. After confirming the install by typing "yes" nothing would happen. After trying every possible solution i then, out of pure frustration (and enormous luck), typed "no" and i was baffled to see this actually worked to install Cashier:

<img width="1111" alt="Screenshot 2022-09-01 at 21 42 34" src="https://user-images.githubusercontent.com/112659513/187998910-5a77c703-c9eb-42f3-92c9-8a36f558ee45.png">

I am not sure i have ever experienced a more frustrating coding issue. If you need more information to replicate this let me know.

**Comment by sandervanhooft** [comment]
Hi @mano-gilissen ,

Ouch, that must have been no fun. We've found the issue and patched it.

I'm somewhat happy to learn that you're the first to actually do this on a production system though.

Releasing the patch in a minute. Thanks for reporting.
