### ISSUE TITLE
Other payment statuses than paid and failed

### ISSUE THREAD

**Issue by Herrald** [mollie/laravel-cashier-mollie#132]
When using Mollie there are a couple of statuses a payment can have: open, canceled, pending, authorized, expired, failed and paid. But when Mollie calls the Laravel webhook, only two statuses are used. Any status other than PAID or FAILED are simply ignored. 

I think this may bring issues regarding subscriptions which are continuing for which is not paid. It might be that I am missing something. Hope you can help

**Comment by sandervanhooft** [comment]
Hi @Herrald, Can you be more specific on the potential issues you're seeing?

**Comment by Herrald** [comment]
Thanks for the swift response! In the webhookcontroller which handles the standard webhook, there is the following switch statement:

src/Http/Controllers/WebhookController.php
```
switch ($payment->status) {
    case PaymentStatus::STATUS_PAID:
        $order->handlePaymentPaid($payment);
        $payment->webhookUrl = route('webhooks.mollie.aftercare');

        /** @var UpdateMolliePayment $updateMolliePayment */
        $updateMolliePayment = app()->make(UpdateMolliePayment::class);
        $updateMolliePayment->execute($payment);

        break;
    case PaymentStatus::STATUS_FAILED:
        $order->handlePaymentFailed($payment);

        break;
    default:
        break;
}
```

This only does something when the status is PAID or FAILED. So, when there is another status than PAID or FAILED it simply does nothing. I.e. when a payment is canceled, there this will not be updated in the database. Which causes a subscription to continue even though there has not been paid for the subscription.

**Comment by sandervanhooft** [comment]
Only first payments, meaning going through Checkout, can get canceled. Only after the first payment gets paid, the subscription starts, so no need to respond to "canceled".

**Comment by Herrald** [comment]
Ah right, I understand. Thank you very much!
