### ISSUE TITLE
First payment status remain open after failed payment

### ISSUE THREAD

**Issue by hjeldin** [mollie/laravel-cashier-mollie#137]
Hi,
we're observing on our databases that all non "paid" payments remain open indefinitely.
Webhooks are called correctly and do not fail.

![Screenshot from 2022-10-24 16-59-16](https://user-images.githubusercontent.com/922567/197559232-65394965-4c64-42d2-9d06-217741087d46.png)

We traced the issue to [FirstPaymentWebhookController](https://github.com/mollie/laravel-cashier-mollie/blob/main/src/Http/Controllers/FirstPaymentWebhookController.php) in which only the "paid" payload from mollie yields an update onto the database via `$order = (new FirstPaymentHandler($payment))->execute();`

Is this intended behaviour? 

Thanks.

**Comment by sandervanhooft** [comment]
Indeed, this is by design. It only makes sense to handle mandated failed payments, not first ones.
