### ISSUE TITLE
Receive order model on first payment

### ISSUE THREAD

**Issue by christianschoenmakers** [mollie/laravel-cashier-mollie#144]
When a (single charge) order is made, the user selects a billing- and shipping address in checkout. 

Both addresses are saved to the Addresses model. The Order model (a custom Model extending the Laravel\Cashier\Order\Order model) has a MorphToMany relation to both adresses with a Pivot value for the type (billing or shipping). 

The $charge->create() function returns the Order model when the payment is on an existing customer, but a 'RedirectToCheckoutResponse' if this is the first payment. Because of that, I'm not able to save the addresses on a customers first payment. 

Is it possible to create a function to receive the Order model from the newCharge() method? 

Code to attach a shipping address to an order (based on an existing shipping address ID). 
```
    if(is_a($result, Order::class)){

      $shippingAddress = Address::findOrFail($request->get('shippingAddress'));
      $result->shippingAddress()->syncWithPivotValues([$shippingAddress->id], ['type' => 'shipping']);

    }
```

**Comment by sandervanhooft** [comment]
Hi @christianschoenmakers ,

That's impossible, the Order is only created after the first payment was successful

**Comment by sandervanhooft** [comment]
You however could still save the address on the billable model or another dedicated model.

**Comment by christianschoenmakers** [comment]
@sandervanhooft Thank you for your fast reply and suggestion, will try it.
