### ISSUE TITLE
Testing Subscriptions in phpunit

### ISSUE THREAD

**Issue by RemiHin** [mollie/laravel-cashier-mollie#146]
I'm trying to figure out how to test my subscriptions.

In phpunit i can create a RedirectResponse, but how do i fake a webhook response?
How do i create an active subscription in a test?
Is there any documentation on this? Is it even possible?

any help would be much appreciated.

**Comment by sandervanhooft** [comment]
Hi @RemiHin ,

That's a lot of questions. What use case you want to cover first?

**Comment by RemiHin** [comment]
Basically what I need to know:
How do I create an active subscription in my phpunit test.

**Comment by sandervanhooft** [comment]
This may be a good place to start:

https://github.com/mollie/laravel-cashier-mollie/blob/c17ff02ff5c24ddec128aab218e8da0bec069760/tests/database/factories/SubscriptionFactory.php#L10-L22

**Comment by RemiHin** [comment]
That was a perfect place to start. Thanks! I got it now
