### ISSUE TITLE
All transactions in a period

### ISSUE THREAD

**Issue by GinJus** [mollie/laravel-cashier-mollie#147]
Hi,

Is it possible to get all the 'paid' subscriptions (of all users) between dates for a administration panel?

When I make a custom query on the 'orders' table I won't receive the renewed subscriptions. Also it isn't clear if the renewed subscription are paid or failed.

Thank you.

**Comment by sandervanhooft** [comment]
Hi,

This is not supported out of the box. If you need something like this there are two options:

- listen for the related events and create a (projection) table specifically for this need
- make some kind of join query across the `subscriptions`, `order_items` and `orders`  tables.
