### ISSUE TITLE
Missing Mollie payment in OrderPayment[Paid|Failed] events

### ISSUE THREAD

**Issue by bobab12** [mollie/laravel-cashier-mollie#152]
Is there any reason `OrderPayment[Paid|Failed]` don't include the Mollie payment object, while `FirstPayment[Paid|Failed]` do? I would like to store the settlement amounts with my local payment records and having access to it would greatly simplify the implementation.

It would be awesome if this could be made available in a future version.

**Comment by voicecode-bv** [comment]
@sandervanhooft if you have time, can you please look into this? We also like to store the settlement amounts in our own database. Thank you! :)
