### ISSUE TITLE
Recurring subscriptions failed because of deleted coupon

### ISSUE THREAD

**Issue by jessedewild** [mollie/laravel-cashier-mollie#153]
I deleted a coupon that still had linked redeemed_coupons to it. Now all the recurring payments have failed. Will it retry to create a payment now?

I removed all the redeemed_coupons from the database, so the error should not happen again. But will the payments automatically try again? Or else, how can I retry by hand?

In the database, the Subscription (cycle_started_at, cycle_ends_at) did not change, so I am worried that there will be a big issue now.

**Comment by sandervanhooft** [comment]
Hi @jessedewild ,

What version are you using?

`cashier:run` will process any unprocessed order items that are due into an order and payment. So a good place to start is looking at the related records in the order_items table.

What can you find there?

**Comment by jessedewild** [comment]
I see! Thanks a lot for your help! It automatically made orders again indeed!

**Comment by sandervanhooft** [comment]
No problem, enjoy!
