### ISSUE TITLE
Subscription without Mollie?

### ISSUE THREAD

**Issue by GertTimmerman** [mollie/laravel-cashier-mollie#158]
So, i have a couple of customers who cannot pay via Mollie because some other department have to approve the invoice and than they will pay it invoice. I am quite struggeling with this types of subscription. I manually add these subscriptions to the database, but it does not work quite well. 

What is the best way to add these subscriptions?

**Comment by GertTimmerman** [comment]
Maybe there is a solution to just make a one-time payment (for example a 1 year subscription) with a payment link via Mollie? So we can send that payment link to the clients and when it is paid, it will automatically reflect on cashier?

**Comment by sandervanhooft** [comment]
Hi @GertTimmerman ,

We're looking into this one. Officially it's not supported as of yet. Besides the first payment, how would subsequent payments be handled ideally?

**Comment by Naoray** [comment]
Hi @GertTimmerman,

Today, @sandervanhooft and I had a conversation regarding the issue you raised. Unfortunately, we do not currently support payment links via subscription. However, we understand that this feature would be useful to you and we are actively exploring the possibility of adding it in a future version. Please note that I cannot provide a definite timeline for when this feature will be available.

In the meantime, there is a potential workaround that might be helpful. You could create a link within your app that will set up a new subscription for your users when they click on it. If you could provide me with more details on how you onboard new customers, I might be able to offer further assistance in implementing this workaround. Thank you for bringing this to our attention and we appreciate your patience as we work to enhance our product.

**Comment by Naoray** [comment]
Hi @GertTimmerman,

> When the customer want to renew their subscription they have to do the same again.

If the customer has to keep visiting the link every time the subscription renews, it's like making separate one-off payments each time. You could use the [charges](https://www.cashiermollie.com/04-charges.html) feature of this package to implement this as a workaround. And if you want to receive automatic reminders for payment or get the payment link by email, you can simply create a new `PaymentLinkSubscription` model to keep track of payments.
