### ISSUE TITLE
Can't retry failed payments

### ISSUE THREAD

**Issue by nicolas-t** [mollie/laravel-cashier-mollie#161]
Hello,

Often Mollie will reject subscription's monthly payments without reason. 
It's annoying since cashier then automatically cancels the subscription.
When I want to retry the failed payment as described [here](7cdff586b4e3d80e6d1318ed635b53834e560139) I get the error `410: Gone: The mandate is no longer available`

Is it the expected behavior, what are the best practices in that case ?

Thanks

**Comment by sandervanhooft** [comment]
Hi @nicolas-t ,

Thanks for reaching out.

Easiest is to have the customer update the payment method in order to obtain a new mandate ([docs](https://www.cashiermollie.com/06-customer.html#updating-customer-payment-method)). After that, retry the payment.

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.

**Comment by nicolas-t** [comment]
Thanks for your answer.

So there is no way to retry the payment before the invalidation of the mandate ? 
I noticed that often the customer is able to resubscribe with the same card so updating the card might not always be required?

**Comment by sandervanhooft** [comment]
Hi @nicolas-t ,

A payment can fail if either there's insufficient funds, or if the mandate is no longer valid.

One thing you could do is email the customer, ask to fix it (ensure enough funds/update payment method), then retry. The retry could be scheduled, triggered by the payment method update, or an action performed by the customer.
