### ISSUE TITLE
Call to undefined method Symfony\Component\HttpFoundation\Response::header()

### ISSUE THREAD

**Issue by jeroenrosendaal** [mollie/laravel-cashier-mollie#163]
When Mollie is calling the ```WebhookController``` it's causing an error like below
```Call to undefined method Symfony\Component\HttpFoundation\Response::header() in /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167```

When swapping ```Symfony\Component\HttpFoundation\Response``` for ```Illuminate\Http\Response``` in the controller files i'm not getting the error anymore.

**Comment by Naoray** [comment]
Hello @jeroenrosendaal,

Could you please let me know which version of Laravel and laravel-cashier-mollie you are currently using? Also, could you specify when exactly the error occurs, for example, during the first payment or some other time? Thank you.

**Comment by jeroenrosendaal** [comment]
Hi @Naoray

I'm using:
 - Laravel 8
 - laravel-cashier-mollie v2

The error occurs when mollie returns to the application and is hitting one of the controllers (`AfterCareWebhookController`, `FirstPaymentWebhookController`, `WebhookController`)

**Comment by Naoray** [comment]
Hello @jeroenrosendaal,

Would you be able to provide me with the exact version of laravel-cashier-mollie that you are using, please? I have been unable to reproduce the error so far. Thank you.

**Comment by jeroenrosendaal** [comment]
Hi @Naoray 

The exact version is ```v2.6.1```

**Comment by Naoray** [comment]
@jeroenrosendaal what’s your `mollie/laravel-mollie` version?

**Comment by jeroenrosendaal** [comment]
@Naoray ```mollie/laravel-mollie v2.16.0```

**Comment by sandervanhooft** [comment]
Hi @jeroenrosendaal ,

We're unable to reproduce the error here with these package versions.

Can you verify that the `cors` middleware is disabled on the webhook route, and see whether any other middleware could be causing the problem? I.e. no auth checks should be applied to these requests.

**Comment by jeroenrosendaal** [comment]
Hi @sandervanhooft 

I checked my middleware and there was indeed a middleware that was causing this problem.
Thanks for pointing it out.

**Comment by sandervanhooft** [comment]
No problem, glad you solved it. Enjoy!
