### ISSUE TITLE
Testing a failed SEPA payment. (OrderPaymentFailedDueToInvalidMandate)

### ISSUE THREAD

**Issue by jeroenrosendaal** [mollie/laravel-cashier-mollie#168]
Hi,

i'm trying to implement some kind of logic that wil show a button/form for updating your payment method based on the documentation. ([https://www.cashiermollie.com/14-retry.html#subscriptions-and-failed-payments](https://www.cashiermollie.com/14-retry.html#subscriptions-and-failed-payments))

I'm able to trigger the `OrderPaymentFailed ` event but not the `OrderPaymentFailedDueToInvalidMandate` event.

Is there a way to test a failed SEPA payment for example due to an invalid card?

Thanks,

**Comment by sandervanhooft** [comment]
Hi @jeroenrosendaal,

Can you share an example of what you have tried so far?

I'd probably go with dispatching the event manually using Laravel's `event(...)` helper function.

**Comment by Naoray** [comment]
@jeroenrosendaal if you want to trigger the `OrderPaymentFailedDueToInvalidMandate` Event manually and update the `Order` accordingly. You could also just call `$order->handlePaymentFailedDueToInvalidMandate()` which will handle the update of the order data for you

**Comment by jeroenrosendaal** [comment]
@Naoray Interesting didn't thing about that. Thanks!
