### ISSUE TITLE
Date casting issues Laravel upgrade from 8.x to 9.x

### ISSUE THREAD

**Issue by ixperiencenl** [mollie/laravel-cashier-mollie#170]
I recently upgraded a project from Laravel 8 to Laravel 9, and now I get the following error:
`Call to a member function isFuture() on string in file /home/michel/Projects/cardatabase/vendor/mollie/laravel-cashier-mollie/src/Subscription.php on line 129`

The date casting in this model is done per Laravel 10 instruction, like this:
`protected $casts = [
        'trial_ends_at' => 'datetime',
        'cycle_started_at' => 'datetime',
        'cycle_ends_at' => 'datetime',
        'ends_at' => 'datetime',
    ];
`

In laravel 8, this worked fine. However, in Laravel 9 this throws the above error.
Changing the casts to the following solves the issue:
`
protected $dates = [ 'trial_ends_at', 'cycle_started_at', 'cycle_ends_at', 'ends_at', ];
`

Anyone an idea in why this is happening?
Using PHP 8.1 by the way.

**Comment by Naoray** [comment]
Hi @ixperiencenl,

which version of laravel-cashier-model are you using?

**Comment by ixperiencenl** [comment]
2.7

**Comment by Naoray** [comment]
@ixperiencenl does the bug still persist?
