### ISSUE TITLE
Swap plan (upgrade) and pay immediately 

### ISSUE THREAD

**Issue by jeroenrosendaal** [mollie/laravel-cashier-mollie#171]
Hi, 

is it possible to swap your plan and pay directly for the extra costs (if it's an upgrade)? 

So after ```$user->subscription('main')->swap('other-plan-id');``` you go straight to the mollie checkout? 
Now it's processed within the order itself.

Thanks,

**Comment by sandervanhooft** [comment]
H @jeroenrosendaal ,

Any surplus costs are incurred directly using a mandated payment. No need to go through the checkout. The only caveat is that it can take a while for the payment to reach its definitive state (paid or failed).
