### ISSUE TITLE
Best practices changing prices of subscription plans

### ISSUE THREAD

**Issue by timvandijck** [mollie/laravel-cashier-mollie#173]
I was going through the docs and couldn't get a clear answer to how you should handle price changes.

There are two scenario's I want to cover:

1) Temporary price changes (discounts), for example on Black Fridays.
For this I guess an automatically applied coupon could be used.

2) Real/"permanent" price changes: we might want to update prices, both up or down.
Is it just as simple as updating the price in the config file and will the user be charged the new price for their next cycle?

If we want to grandfather users so they keep their "old" price. Would it be best to just create a new plan and keep the old clients on the old plan?

**Comment by Naoray** [comment]
Hi @timvandijck,

For temporary price changes such as discounts on special occasions like Black Friday, utilizing coupon codes is indeed the best approach. 

For permanent price changes, updating the price in the config file is a simple way to change the price for all users. However, keep in mind that the new price will be applied during the next billing cycle for all users, and they will be charged accordingly.

If you want to keep old clients on the old pricing plan and grandfather them, creating a new pricing plan for new customers and keeping the old clients on the old plan is the best approach. This way, the old clients can continue with their old pricing plan while new customers can be charged with the new pricing plan.

Does this sufficiently answer your questions?

**Comment by timvandijck** [comment]
@Naoray these are indeed the answers/validation I was looking for. Thank you for taking the time to answer my questions!
