### ISSUE TITLE
Question: Mollie changes: Mandate after first payment for credit card payments

### ISSUE THREAD

**Issue by voicecode-bv** [mollie/laravel-cashier-mollie#178]
Hi there, 

We've received a notification from Mollie about an upcoming change: mandates given after the first payment for credit card payments. It also mentions that if you follow the best practices, no updates on our end should be necessary. Just to check, does this mean we're good when using this package?

Cheers!

**Comment by fjbender** [comment]
To add a slight bit of context: The change we're making it that the `mandateId` is not returned anymore immediately after creating the payment, but only after the payment actually has been paid (which is already the case for many, but not all methods).

In this package we have `FirstPaymentHandler::execute()` referring to the `mandateId`, but as I'm not too familiar with Laravel Cashier, I'm not sure when exactly this Handler is being executed.

@sandervanhooft can shed some light on that with this additional context, I'm sure.

**Comment by sandervanhooft** [comment]
Let me dive into this and get back to you.

**Comment by sandervanhooft** [comment]
The FirstPaymentHandler is triggered when Mollie calls Cashier's webhook with status "paid".

@fjbender is correct: the handler then retrieves the Mollie payment and stores the mandate id locally. So looks to me we're all good!

**Comment by fjbender** [comment]
Perfect, thanks!
