### ISSUE TITLE
Multiple swaps creates too many orders and payments

### ISSUE THREAD

**Issue by michelterstege81** [mollie/laravel-cashier-mollie#179]
![Cashier multiple swaps](https://github.com/mollie/laravel-cashier-mollie/assets/118480982/0979298c-2353-4dfd-b14f-6b5a090a4f1c)

When running the swap command multiple times in a row on a subscription (during the trial period) new orders and payments are created with incrementing periods (see description_extra_lines).

I first created a subscription (orderable_id = 4) resulting in:

- id 19: a scheduled order_item with no order_id yet scheduled for the next cycle. Which would be the first cycle after the trial period of 30 days. (which is removed later during the swap, so not visible anymore in the screenshot)
- id 20: The free trial period 21/6 -21/7 price 0
- id 21: a 1 cent first payment to setup the mandate

and then did multiple swaps using:
```
$tenant->subscription('main')->swap($plan);
```

- id 19 is removed, which seem to be expected
- then on every swap a new order item is created that is scheduled, but no order id yet (like id 27)
- but also every time an order_item is created with with an order_id and I can see the payments appear at Mollie as pending with a collection date of the day after tomorrow.

So if I create a subsciption today with a trial period of 30 days and do 3 swaps I see 3 collections planned at Mollie about to occur the day after tomorrow.

And in the order items I see items appear for the periods 21/7 - 21/8, 21/8 - 21/9 and 21/9 - 21/10. 

I would have expected that there would only be 1 order_item scheduled. And that would then be for the first paid cycle after the trial. That item should then have a unit_price of the latest selected plan. 

Now, looking at my Mollie account, it seems that the tenant is going to be charged 7000, 72000 and 7000 on the 23th of June. So he would pay for 3 periods at once and it would be the wrong amounts.

Note:
When calling swap I see that restartCycleWithModifications is called on the Subscription model. It gets in the if statement because we're on trial and so a new orderitem is created. This is what I expect.

Then it gets in the if invoiceNow statement and the orderItem is immediately processed. 

This does not seem right. Is it?

In the Order model $item->process is called. This results in processOrderItem being called on the subscription, which in turn schedules a new order item for the next cycle.

So after a few swaps we are months ahead and have multiple wrong payments.

**Comment by sandervanhooft** [comment]
Hi @michelterstege81 ,

Thanks for reporting. Can you share a config sample and the code (incl the trial setup etc) that triggers this issue, so we can reproduce it here and take it from there?

**Comment by michelterstege81** [comment]
Hi @sandervanhooft ,

I did not really make changes in cashier.php or cashier_plans.php except for defining a plan name, price and description.

I just call:
```
$tenant->subscription('main')->swap($plan);
```
3 times in 5 minutes during the first day of a 30 day trial period.

Where $tenant is my billable model.

Then in the package code I can see the following:

In Subscription.php
```
public function swap(string $plan, $invoiceNow = true)
```
calls
```
$this->restartCycleWithModifications($applyNewSettings, now(), $invoiceNow);
```
there in
```
if ($this->onTrial()) {
```
schedules a new OrderItem
```
// Reschedule next cycle's OrderItem using the new subscription settings
$orderItems[] = $this->scheduleNewOrderItemAt($this->trial_ends_at);
```
which is then  (I think incorrectly) immediately processed:
```
if ($invoiceNow) {
    $order = Cashier::$orderModel::createFromItems($orderItems);
    $order->processPayment();
}
```
then in Order.php
```
$order = Cashier::$orderModel::createFromItems($orderItems);
```
calls
```
if ($process_items) {
    $item->process();
}
```
In OrderItem.php this results in
```
$result = $this->orderable->processOrderItem($this);
```
where orderable is a subscription. 
So in Subscription.php
```
public static function processOrderItem(OrderItem $item)
```
is called and a new OrderItem is scheduled
```
$subscription->scheduleNewOrderItemAt($subscription->cycle_ends_at);
```

I can work around it by calling swap with the second parameter ($invoiceNow) set to false if my code checks if the tenant is on trial period, but I expected the Subscription.php to handle that.

I would say that it would be logical if the invoiceNow part was done before applying the actual swap.

**Comment by sandervanhooft** [comment]
Hi @michelterstege81 ,

Thank you for raising this issue and the detailed report.

I have prepared a patch here: #182, always preventing orders from being created while on trial. Before releasing, can you double check that this is solving your issue?

**Comment by michelterstege81** [comment]
Hi @sandervanhooft,

Thanks for the fast response. I just checked and this indeed solves the issue!

**Comment by sandervanhooft** [comment]
Great! I'll do an official release after the weekend. Enjoy!

**Comment by sandervanhooft** [comment]
The patch was just released. Thanks @michelterstege81 ! 

https://github.com/mollie/laravel-cashier-mollie/releases/tag/v2.7.1
