### ISSUE TITLE
Metered billing example

### ISSUE THREAD

**Issue by dejagersh** [mollie/laravel-cashier-mollie#185]
Hi there,

The option for metered billing is mentioned, but no examples are provided. Has anyone been able to get this to work? I would love to see an example!

Thanks,
Johan

**Comment by Naoray** [comment]
Hi @dejagersh,

another user asked this question already. Take a look at the answer I gave [here](https://github.com/mollie/laravel-cashier-mollie/issues/151#issuecomment-1432726192).

> You can implement metered billing by configuring the `order_item_preprocessors` in your `cashier_plans` config. A `MeteredBillingPreprocessor` could look something like the following:
> 
> ```php
> use Laravel\Cashier\Order\BaseOrderItemPreprocessor;
> use Laravel\Cashier\Order\OrderItem;
> use Laravel\Cashier\Order\OrderItemCollection;
> 
> class MeteredBillingPreprocessor extends BaseOrderItemPreprocessor
> {
>     /**
>      * @param  \Laravel\Cashier\Order\OrderItemCollection  $items
>      * @return \Laravel\Cashier\Order\OrderItemCollection
>      */
>     public function handle(OrderItemCollection $items)
>     {
>         // You can add, remove or modify order items here.
>         // Each order item relates to 1 line on the invoice.
>         
>         // For metered billing, you typically:
>         // 1. fetch metered data from within your app
>         // 2. apply it to the order items
>         // 3. if necessary, notify the meters that the costs were incurred/reset the meters
>         
>         $owner = $items->owners()->first();
>         
>         $meters = $owner->getMeters();
>         $meterItems = $meters->map(function ($meter) {
>             return OrderItem::make([
>                 'process_at' => now(),
>                 'description' => $meter->description,
>                 'currency' => $meter->currency,
>                 'unit_price' => $meter->unit_price,
>                 'quantity' => $meter->quantity,
>                 'tax_percentage' => $this->tax_percentage, 
>             ]);
>         });
>         
>         $items = $items->concat($meterItems);
>         
>         $owner->resetMeters(); // optionally put this in a separate ResetMetersPreprocessor right after the PersistOrderItemsPreprocessor
>         
>         return $items;
>     }
> }
> ```
> 
> Please keep in mind that, currently, adding preprocessors to the first payment is not supported. Therefore, you may still need to reimburse the user for any overpaid amount during the first billing cycle. Additionally, scheduling the payment at the end of a cycle is not mandatory for metered billing, and it's not currently possible with Laravel-Cashier-Mollie. Nonetheless, you can still use metered billing by asking users to pay a fixed upfront amount and adding the metered component to the invoice for the next billing cycle. We're actively working on ways to make these processes easier in the next versions of our package.
>
> _Originally posted by @Naoray in https://github.com/mollie/laravel-cashier-mollie/issues/151#issuecomment-1432726192_

If you have further questions, please let me know!
