### ISSUE TITLE
[Feature request] Scopes

### ISSUE THREAD

**Issue by voicecode-bv** [mollie/laravel-cashier-mollie#186]
Hi there!

I noticed when working on one of my projects, that we could really benefit from having some scopes to the subscription model. 

There are already some methods to define active, onTrial or onGracePeriod subscriptions, but as far as I have seen, there are no scopes for this. We would use an scopeActive scope for example, to fetch all active yearly subscriptions, so we can reset some monthly restrictions for the subscription's owner. 

Is this something you're willing to help out with?

**Comment by Naoray** [comment]
Hello @voicecode-bv,

I appreciate your suggestion. I have taken the initiative to create a pull request (PR #187) that includes specific scopes for each boolean method found in the Subscription class.

I hope you are satisfied with the changes made!

**Comment by voicecode-bv** [comment]
You've made my day! Thanks for this, really appreciate it!

**Comment by Naoray** [comment]
@voicecode-bv released in the lastest version
