### ISSUE TITLE
Cancelation / grace period longer than billing cycle

### ISSUE THREAD

**Issue by turpoint** [mollie/laravel-cashier-mollie#190]
A client I'm building a project for wants to offer subscriptions where the customer is billed every month. However, when the customer cancels, he must do this 3 months in advance. So if he would cancel today, he would still be billed twice. Looking at the documentation, there is no cancelAt() function to set the end date to a specific point in the future.

I know this scenario is pretty unique, and might not make that much sense, because in that 3 month cancelation period, the customer might just cancel their mandate in their VISA or MasterCard account. This would result in failed payments during the cancelation period. The client knows this is a possibility (and might happen more often that he thinks), but is okay with it.

Is there a way I could easily implement this?

**Comment by sander3** [comment]
@turpoint It's undocumented, but its there: https://github.com/mollie/laravel-cashier-mollie/blob/a8d95555f15861e32ac58497677233032f4fbf5e/src/Subscription.php#L350C21-L350C29

**Comment by Naoray** [comment]
Hello @turpoint,

sorry for not getting back to you earlier!

Currently, we do not support canceling a subscription while still keeping it active in the billing cycle for further billing. We do have a cancelAt() method available, but it only allows setting the cancellation date. Once the cancelAt() method is used, the subscription will be marked as "cancelled" and won't be included in future billing cycles.

You could implement your use case by setting a date column e.g. `should_be_cancelled_on` on the `Subscription` as soon as the user cancels the subscription. Then you can go ahead and schedule a command/job that checks if that`should_be_cancelled_on` is reached. Then you can call the `cancelNow()` method on the subscription.

```php
use Laravel\Cashier\Subscription;

class CancelSubscriptionsImmediately
{
    public function handle(): void
    {
        Subscription::query()
            ->where('should_be_cancelled_on', '<=', now())
            ->cursor()
            ->each(fn (Subscription $subscription) => $subscription->cancelNow());
    }
}

// schedule job
$schedule->job(new CancelSubscriptionsImmediately)->everyDay();
```
    
If you have further questions, please let me know!
