### ISSUE TITLE
Coupon interface missing

### ISSUE THREAD

**Issue by sander3** [mollie/laravel-cashier-mollie#193]
Hi there,

For subscription plans we have the option to move them to the database quite easily due to a interface being used instead of the Plan class directly. A similar way of doing things for coupons is missing.

Since this project tries to follow Semantic Versioning I'd like to know if you are interested in a PR implementing this, since it will be a breaking change for everyone that implemented a custom `CouponHandler`.

**Comment by sander3** [comment]
> Hi @sander3 ,
> 
> To make sure we're on the same page, have you seen this repository contract?
> 
> https://github.com/mollie/laravel-cashier-mollie/blob/main/src/Coupon/Contracts/CouponRepository.php

Hey! Yes I've seen the repository contract. While it does allow me to create a Coupon object on the fly it doesn't do it in the same way as the Plan object where you can just extend a contract to implement the object's desired functions.

**Comment by sander3** [comment]
I went with the easy route of implementing a buildCoupon method on the model instead.

**Comment by sandervanhooft** [comment]
Easier for everyone, thanks for following up! 🚀
