### ISSUE TITLE
Can't find reference how to get the next payment billing date

### ISSUE THREAD

**Issue by handhikadj** [mollie/laravel-cashier-mollie#195]

**Comment by sandervanhooft** [comment]
Hi @handhikadj ,

You could use this field:

https://github.com/mollie/laravel-cashier-mollie/blob/236e4c12ecd91909fa4859c1a8020c2eedabaacc/database/migrations/create_subscriptions_table.php.stub#L28

**Comment by handhikadj** [comment]
@sandervanhooft 
I notice the `cycle_ends_at` field is the total period of the end date. 
for example if we have 6 months of subscription, then the `cycle_ends_at` value will be 08 February 2024 (calculated from the time of this comment is created). I think this is taken from the Interval. 
hope this makes sense to you
