### ISSUE TITLE
Undefined property: stdClass::$actions at /vendor/mollie/laravel-cashier-mollie/src/FirstPayment/FirstPaymentHandler.php:103

### ISSUE THREAD

**Issue by handhikadj** [mollie/laravel-cashier-mollie#202]
I'm getting this issue using v2.9.0 on the log
this happens right after/some seconds after the recurring payment runs (`Cashier::run();`) especially the recurring payments of SEPA payments

**Comment by Naoray** [comment]
Hi @handhikadj,

could you parse the whole error log please?

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.

**Comment by jivanrij** [comment]
I'm also having this issue, with 2.9.0 and 2.10.0. 

I'm currently looking for the reason when stumbling on this ticket. I've tracked it down to FirstPaymentHandler::extractActions()

<img width="1629" alt="Screenshot 2023-10-08 at 15 12 59" src="https://github.com/mollie/laravel-cashier-mollie/assets/1710463/ac31ba21-bf3c-4822-804e-1bcb6a2a34e2">

<img width="1155" alt="Screenshot 2023-10-08 at 15 13 05" src="https://github.com/mollie/laravel-cashier-mollie/assets/1710463/3f4c800a-e9eb-4aa9-92f3-d9532f88fd86">

**Comment by jivanrij** [comment]
One update, not a solution though. But perhaps an answer for @handhikadj. Check the comments in the else


```
    // \Laravel\Cashier\FirstPayment\FirstPaymentHandler
    protected function extractActions()
    {
        $payment = Cashier::$paymentModel::findByPaymentId($this->molliePayment->id);

        \Illuminate\Support\Facades\Log::channel('mollie')->info('payment', ['payment model' => $payment->first_payment_actions]);

        if (isset($payment) && ! is_null($payment->first_payment_actions)) {
            $actions = $payment->first_payment_actions;
        } else {
            // When developing in test mode, and also resetting the database with a high frequency, it's possible that you get callbacks 
            // from Mollie that can't be found in the database. In that case $this->molliePayment->metadata does not exist.
            $actions = $this->molliePayment->metadata->actions;
        }

        return collect($actions)->map(function ($actionMeta) {
            return $actionMeta->handler::createFromPayload(
                object_to_array_recursive($actionMeta),
                $this->owner
            );
        });
    }
```

**Comment by Naoray** [comment]
> One update, not a solution though. But perhaps an answer for @handhikadj.
> 
> When `\Laravel\Cashier\FirstPayment\FirstPaymentHandler::extractActions()` is called `metadata` doesn't exist if the code runs due to a Mollie callback for a Payment that is removed from the database because of testing, debugging, migrate:fresh or stuff like that. That's an explanation for the "Undefined property: stdClass::$actions" message.
> 
> In my case, the Subscription model is still not created. But I guess that's an other issue/ticket. I'll create one for it.

Good point @jivanrij. So the error only popped up in your local env?!

**Comment by Naoray** [comment]
Will close this for now. If anyone can offer more details to this please let me know!

**Comment by sandervanhooft** [comment]
FYI I am dropping the legacy support for that metadata field in #294
