### ISSUE TITLE
Unable to find this in the documentation

### ISSUE THREAD

**Issue by jivanrij** [mollie/laravel-cashier-mollie#205]
I'm working on an implementation and I would like to validate some assumptions, information I can't seem to find in the documentation but hope to have assumed correctly based on the source code of the package.

It's all about the scenario after the first payment of a Subscription is done.

1. Mollie Cashier does not create new OrderLines. Your application needs to do that itself with methods like newSubscription(). So Cashier::run() does nothing unless you have created new subscriptions.
2. Mollie Cashier creates Orders from OrderItems and creates payments @ Mollie with the known mandate id.
3. Mollie Cashier is 'blind' to previous start and end dates of the Subscription. With newSubscription it will simply create a new Subscription with cycle_started_at having a value of that current day. Therefore things like changing the cycle_started_at are best done by event handlers like OrderPaymentPaid.

**Comment by sandervanhooft** [comment]
Assuming you have

- used `$billable->newSubscription(...);`
- redirected the customer to Mollie's hosted checkout
- and the customer has completed the payment in the Mollie hosted checkout:

> 1. Mollie Cashier does not create new OrderLines. Your application needs to do that itself with methods like newSubscription(). So Cashier::run() does nothing unless you have created new subscriptions.

Cashier Mollie handles creating the Order and OrderLines for the first payment/Order. Subsequent Orders are generated from Order Lines that are due, so in case of a subscription that's when the current billing cycle is completed. This processing is triggered by executing `cashier:run` periodically. If there are no order items due, nothing gets processed.

> 2. Mollie Cashier creates Orders from OrderItems and creates payments @ Mollie with the known mandate id.

Yes  - except for the first cycle, which is created from the first Mollie payment which also used to yield the mandate id.

> 3. Mollie Cashier is 'blind' to previous start and end dates of the Subscription. With newSubscription it will simply create a new Subscription with cycle_started_at having a value of that current day. Therefore things like changing the cycle_started_at are best done by event handlers like OrderPaymentPaid.

Using `newSubscription()` you're creating a new subscription, so there are no previous start dates. There is currently no way to override the default start date (`now`), but we're open to review any suggestions/PRs to add this - as long as the use case makes sense.

**Comment by jivanrij** [comment]
@sandervanhooft thanks for your extensive reply :)

Then it seems Cashier Mollie doesn't create new orders in my test scenario. This is what I'm doing:
1. New user, creates a new Subscription for one day. 
2. The user goes through the Mollie payment and comes back on the site. subscribed() and subscribedToPlan() both confirm that my user is in the plan and subscribed. 
3. Then I change the following fields to move the subscription period one day back, to test if Cashier will create a new Order. `subscriptions.cycle_started_at `, `subscriptions.cycle_ends_at `, `orders.processed_at`, `order_items.process_at`, `payments.created_at` & `payments.updated_at`. 
4. Then I would expect Cashier to create a new Order. But nothing happens. 

I guess that is the reason why I was getting the impression you are supposed to create the order yourself. But that assumption (first one) was wrong.

The question I'm left with is, how does Cashier determine when a new Order needs to be created? Based on what data, or what code?

**Comment by sandervanhooft** [comment]
There should be one or multiple OrderItem s with `order_id` `null`, and a `process_at` date in the past.

Some pointers to dig deeper:

https://github.com/mollie/laravel-cashier-mollie/blob/f22df342643e15fbd58544229430eaaa78bdf8d4/src/Cashier.php#L130-L139

https://github.com/mollie/laravel-cashier-mollie/blob/f22df342643e15fbd58544229430eaaa78bdf8d4/src/Order/OrderItem.php#L150-L160

**Comment by Naoray** [comment]
Hi @jivanrij,

Ah, @sandervanhooft beat me a few minutes… anyways. Here is a longer explanation, hope it helps!

The whole determining of Cashier on which Subscriptions to process happens within the `Cashier::run()` method (s. https://github.com/mollie/laravel-cashier-mollie/blob/main/src/Cashier.php#L130). Here we check for all `OrderItems` that should be processed (scope `scopeShouldProcess()` s. https://github.com/mollie/laravel-cashier-mollie/blob/4ec435acd86a0f6708be18458c54170a7f58f183/src/Order/OrderItem.php#L157). The scope returns all `OrderItems` which are not processed (don’t have an `Order` associated s. https://github.com/mollie/laravel-cashier-mollie/blob/4ec435acd86a0f6708be18458c54170a7f58f183/src/Order/OrderItem.php#L120) and are `due()` - have the `process_at` field set to a value in the past s. https://github.com/mollie/laravel-cashier-mollie/blob/4ec435acd86a0f6708be18458c54170a7f58f183/src/Order/OrderItem.php#L147)

**Comment by jivanrij** [comment]
So, on the initial new Subscription Cashier creates 2 OrderLines.
- One for the current payment that will be handled directly. 
- A second one for the next period, that will be handled at the end of this period. 
- When handling the 2nd OrderLine, a 3rd OrderLine will be created that will be picked up after the second period. 
- etc...

Seems as simple as that. I just didn't notice the date on the order_lines was a future date.

Thanks @Naoray and @sandervanhooft
