### ISSUE TITLE
Invoice not available after creating order / creating sepa 

### ISSUE THREAD

**Issue by michelterstege81** [mollie/laravel-cashier-mollie#210]
The OrderInvoiceAvailable event is fired when an order is paid in handleOrderPaymentPaid. This feels a bit weird to me. It means that in my Mollie dashboard I can already see the sepa with status 'in afwachting' and in my frontend I show a 'renews on' date to my subscriber that is already been updated based on the subscription cycle. However I don't have the invoice available yet to show / e-mail to my subscriber.

Also in case the payment fails I would expect that the invoice is already there when the order is created.

I think it would be great if the invoice becomes available after the order is created. So at the start of a cycle the subscriber can directly see the invoice and the status of the invoice. Maybe even the expected date that the amount will be withdrawn from the subscribers bank account, since that information is available in Mollie.

This way you can send an e-mail to the subscriber with the invoice attached and a message that the subscriber can expect the amount to be withdrawn in the upcoming days.

When a payment fails the subscriber can than see which invoice is not paid.

**Comment by sandervanhooft** [comment]
Hi @michelterstege81 ,

Thanks for sharing this. The invoice here actually is closer to what's called a "receipt". 

The wording carried over from other Cashier implementations back in the day. Perhaps Order Created is what you're looking for? In that case the invoice could be considered pro-forma.

Sending out an invoice prior to it getting deducted from the customer's account can be nice UX. On the other hand things can get complicated to integrate when the payment fails. That's a big factor in why we choose to implement it this way.
