### ISSUE TITLE
Order's amount_charged_back never updated

### ISSUE THREAD

**Issue by sander3** [mollie/laravel-cashier-mollie#212]
Hi there,

The `amount_charged_back` column on the Order model is never updated. The payment one is but the order value remains 0.

**Comment by Naoray** [comment]
Hi @sander3,

the `Order`’s `amount_charged_back` indeed isn’t updated anywhere it seems. I will dig a little deeper and let you know what I can find and how we will fix it.

**Comment by Naoray** [comment]
Hi @sander3,

you were right. Somehow the existing column isn’t used anywhere. I’ve gone ahead and added a `amountChargedBack()` method to the `Order` which will likely change into an accessor and be accessible with `$order->amount_charged_back` with the next major release. For now it would technically be a breaking change to override the usage of the column by introducing an accessor...
