### ISSUE TITLE
Payment status Open while payment failed.

### ISSUE THREAD

**Issue by michelterstege81** [mollie/laravel-cashier-mollie#216]
I just tested a subscription in test modus and selected failed. I see in my Mollie account the status is failed. The FirstPaymentFailed also fires. However when handling the redirect_url after the first_payment if I look up the $payment by the $request->payment_id it has status open. Investiging the database also shows open in the mollie_payment_status column.

So in my controller I can only but consider the payment open and redirect to a thank you page. While actually I would like to inform the user about the failed payment on an error page. And maybe add a button there with a link to retry.

Would there be a way to check with Mollie what the real status is? 

Route:
```
Route::get('/check-payment/{payment_id}', [RegistrationController::class, 'checkPayment'])->name('registration.after_payment');
```

Controller:

```
public function checkPayment(Request $request)
    {
        $payment_id = $request->payment_id;

        $payment = Payment::findByPaymentId($payment_id);

        if(!$payment)
        {
            Log::error('Payment with ID '.$payment_id.' not found.');
            abort(404);
        }

        $status = $payment->mollie_payment_status;

        $response = redirect(route('registration.thankyou'));

        /* Check the payment.
           On success redirect to thank you.
           On fail redirect to error page and log details. */
        switch($status)
        {
            case PaymentStatus::STATUS_OPEN:  // THIS CASE GETS EXECUTED WHILE FAILED WAS CHOSEN IN THE MOLLIE PAYMENT SCREEN
                Log::info('Payment with ID '.$payment_id.' has status open.');
                break;
            case PaymentStatus::STATUS_PENDING:
                Log::info('Payment with ID '.$payment_id.' has status pending.');
                break;
            case PaymentStatus::STATUS_AUTHORIZED:
                Log::info('Payment with ID '.$payment_id.' has status authorized.');
                break;
            case PaymentStatus::STATUS_CANCELED:
                Log::info('Payment with ID '.$payment_id.' has status canceled.');
                break;
            case PaymentStatus::STATUS_EXPIRED:
                Log::info('Payment with ID '.$payment_id.' has status expired.');
                break;
            case PaymentStatus::STATUS_PAID:
                Log::info('Payment with ID '.$payment_id.' has status paid.');
                break;
            case PaymentStatus::STATUS_FAILED:
                Log::info('Payment with ID '.$payment_id.' has status failed.');
                $response = redirect(route('registration.payment.error'));
                break;
            default:
                Log::warning('Unknown PaymentStatus ('.$status.') for payment with ID '.$payment_id);
        }

        return $response;
    }
```

**Comment by michelterstege81** [comment]
Thanks. This works. Only had to change 

```
$status = $payment->mollie_payment_status;
```

to

```
$status = $payment->status;
```

**Comment by michelterstege81** [comment]
I solved the retry mechanism by adding a link on the payment failed page back to the subscribe form. On subscription I check that the user already exists and that there is no subscription. Then just create a new subscription which prepares a new Mollie payment and a redirect to it.

So that's solved :)

**Comment by Naoray** [comment]
Good to know that you solved that @michelterstege81.

If there is any other question, feel free to open another issue.

**Comment by Naoray** [comment]
@michelterstege81 I’ve added it to our internal roadmap, but it’s currently not considered a bug.

You can solve this by listening to the `FirstPaymentFailed` and `OrderPaymentFailed` and update the status yourself for now.
