### ISSUE TITLE
Wrong Webhook URL?

### ISSUE THREAD

**Issue by MrMooky** [mollie/laravel-cashier-mollie#22]
We just switched the Test-Key with the Live-Key and tested a first payment. Everything went fine while using the Test-Key. But now with the Live-Key, the webhooks seem to not work correctly in the first place.

It took a while (7 minutes) for the webhooks to be send. I know that this is not really in the scope of this package. The actual question is regarding another log in the transaction.

It says (in German):

> Aktualisieren Sie webhook URL von 'https://www.domain.de/webhooks/mollie/first-payment' zu 'https://www.domain.de/webhooks/mollie/aftercare'.

This was a first-time payment with credit card. According to `cashier.php`, the aftercare endpoint is only used for refunds and chargebacks (`aftercare_webhook_url`).

**Comment by sandervanhooft** [comment]
What events is Mollie's dashboard showing for this payment?

**Comment by MrMooky** [comment]
Apparently, the correct ones:

<img width="847" alt="Screenshot 2021-12-06 at 12 17 49" src="https://user-images.githubusercontent.com/3603346/144837092-c561cbcd-f537-4d03-8006-618c53431271.png">

**Comment by MrMooky** [comment]
Same for the `first_payment` > `redirect_url`:

![cashier-mollie](https://user-images.githubusercontent.com/3603346/144837885-f0874b1b-b638-4b12-a63c-fb35f45ad2db.jpg)

**Comment by sandervanhooft** [comment]
So what's your question? 😀

**Comment by sandervanhooft** [comment]
That "Aktualiseren Sie..." reads like an imperativus, but I think it's meant as "webhook url was updated". Bad translation? My German is lacking...

**Comment by MrMooky** [comment]
I wanted to know if this is expected behaviour as it seems like a wrong endpoint?  Why is the webhook url `aftercare` and not `first-payment` as stated in the `cashier.php`? Mollie or Cashier clearly makes a redirect or anything...

Having live payments with webhook messages I cannot retrace myself is not that funny to me.

**Comment by MrMooky** [comment]
> That "Aktualiseren Sie..." reads like an imperativus, but I think it's meant as "webhook url was updated". Bad translation? My German is lacking...

It would translate to "Please update your url redirect from a to b".

**Comment by sandervanhooft** [comment]
Yeah I thinkt that German text is seriously misguiding, I'll contact Mollie about this.

Rest assured the webhook url update is correct behavior. 👍

**Comment by MrMooky** [comment]
Ok, that's just what I wanted to hear. Thanks. :)

**Comment by MrMooky** [comment]
I just switched the dashboard from German to English and yeah, it says "Updated the webhook URL from ...". The German translation is just misleading.

**Comment by sandervanhooft** [comment]
No problem, thanks for reporting! Enjoy!
