### ISSUE TITLE
Integrity constraint violation: 1048 Column 'cycle_started_at' cannot be null

### ISSUE THREAD

**Issue by jeroenrosendaal** [mollie/laravel-cashier-mollie#221]
Hi, I'm getting the following SQL error while running `Cashier:run`. 

```SQL
## in Connection.php line 712:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cycle_started_at' cannot be null (SQL: update `lc_subscriptions` set `cycle_started_at` = ?, `cycle_ends_at` = 2025-01-11 11:14:51, `scheduled_order_item_id` = 267264, `lc_  
subscriptions`.`updated_at` = 2024-01-11 11:14:51 where `id` = 14)  

## In Exception.php line 18:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cycle_started_at' cannot be null

## In PDOStatement.php line 117:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cycle_started_at' cannot be null
```

I can't figure out where the code pulls the `cycle_start_at` field from.   
Can somebody point me in the right direction?

**Comment by sandervanhooft** [comment]
Hi @jeroenrosendaal ,

Thanks for reporting. What version of Cashier Mollie are you on?

**Comment by jeroenrosendaal** [comment]
`"mollie/laravel-cashier-mollie": "^2.0"`
`"mollie/laravel-mollie": "^2.0",`

**Comment by sandervanhooft** [comment]
What specific versions are used in your installation?

You can use `composer show` to list all versions or `composer show <package>` to view the details on a specific package.

**Comment by jeroenrosendaal** [comment]
@sandervanhooft 
```
mollie/laravel-cashier-mollie      v2.6.1 
mollie/laravel-mollie                    v2.16.0
mollie/mollie-api-php                  v2.39.0
```

**Comment by sandervanhooft** [comment]
Can you try and bump cashier to the latest version (`2.11.0`), so we're on the same page?

Typically, the `cycle_started_at` is managed by the `Subscription` model.

Have you made any modifications? Any custom Eloquent/database drivers?

**Comment by sandervanhooft** [comment]
https://github.com/mollie/laravel-cashier-mollie/blob/main/src/Subscription.php

**Comment by jeroenrosendaal** [comment]
@sandervanhooft We are not yet on PHP8.2 so updating to the latest version is not going to work for now. I'm currently trying to bump up the PHP version so we can upgrade.

**Comment by jeroenrosendaal** [comment]
@sandervanhooft I've updated Cashier but running into another problem. I need to update the `aftercare_webhook_url` but the changes doesn't go trough. I seems that the domain (public domain) I manually added is replaced with my local domain. If I change the url from '/webhooks/mollie/aftercare` to `/webhooks/mollie/aftercase123` the change is visible. 

Like:
`'/webhooks/mollie/aftercare'` -> `'/webhooks/mollie/aftercare1234'`
`'https://my-public-domain.com/webhooks/mollie/aftercare'` ->`'https://localhost.test/webhooks/mollie/aftercare'`

I'm logging `$payment->webhookUrl` in the `FirstPaymentWebhookController`.

**Comment by sandervanhooft** [comment]
Hi @jeroenrosendaal ,

Was the original issue fixed?


Regarding the webhook urls being relative to your APP_URL: if you point these to an external domain, Cashier will not receive updates from Mollie. If you need to test the integration, I can highly recommend using a tunnelling service like [ngrok](https://ngrok.com) to temporarily expose the webhooks.

**Comment by jeroenrosendaal** [comment]
@sandervanhooft No the original issue is not fixed. I updated everything but due to the new error i'm not able to test the original error. I'm using NGROK but cashier keeps using my local domain. I cleared the config cache but without success.

**Comment by jeroenrosendaal** [comment]
And when I try to retrieve `route('webhooks.mollie.aftercare')` trough Laravel tinker i'm getting the correct url, with the NGROK url.

**Comment by jeroenrosendaal** [comment]
@sandervanhooft The `Cashier->aftercasewebhookUrl()` strips out the domain part.

**Comment by jeroenrosendaal** [comment]
My `cashier.php` looks like this:
```
<?php

return [

    /**
     * The default webhook url is called by Mollie on payment status updates. You can use either a relative or
     * absolute url.
     */
    'webhook_url' => config('app.url') . '/mollie/webhook',

    /**
     * The default aftercare webhook url is called by Mollie on refunds and chargebacks. You can use either a relative or
     * absolute url.
     */
    'aftercare_webhook_url' => config('app.url') . '/webhooks/mollie/aftercare',
```

**Comment by jeroenrosendaal** [comment]
@sandervanhooft 
For now I have found a workaround for the aftercare hook. The original question stays. If update cashier to the latest version without but the error remains. I can share the records of the order and orderItems
```sql

INSERT INTO `lc_order_items` (`id`, `process_at`, `orderable_type`, `orderable_id`, `owner_type`, `owner_id`, `description`, `description_extra_lines`, `currency`, `quantity`, `unit_price`, `tax_percentage`, `order_id`, `created_at`, `updated_at`) VALUES (NULL, '2024-01-12 00:00:00', 'Laravel\\Cashier\\Subscription', '35', 'App\\Models\\User', '6059', 'year_subscription_bronze', '', 'EUR', '1', '1995', '0.0000', NULL, '2024-01-12 00:00:00', '2024-01-12 00:00:00')
INSERT INTO `lc_orders` (`id`, `owner_type`, `owner_id`, `number`, `currency`, `subtotal`, `tax`, `total`, `balance_before`, `credit_used`, `total_due`, `amount_refunded`, `amount_charged_back`, `mollie_payment_id`, `mollie_payment_status`, `processed_at`, `created_at`, `updated_at`) VALUES (NULL, 'App\\Models\\User', '6059', '2024-0000-0046', 'EUR', '1', '0', '1', '0', '0', '1', '0', '0', 'tr_1234', 'paid', '2024-01-08 22:58:42', '2024-01-08 22:58:42', '2024-01-08 22:58:42')


```

**Comment by jeroenrosendaal** [comment]
@sandervanhooft 

For now if found a workaround for the aftercare url.

The record below is causing the error of the original question. 

```sql
INSERT INTO `lc_order_items` (`id`, `process_at`, `orderable_type`, `orderable_id`, `owner_type`, `owner_id`, `description`, `description_extra_lines`, `currency`, `quantity`, `unit_price`, `tax_percentage`, `order_id`, `created_at`, `updated_at`) VALUES (NULL, '2024-01-12 00:00:00', 'Laravel\\Cashier\\Subscription', '35', 'App\\Models\\User', '6059', 'year_subscription_bronze', '', 'EUR', '1', '1995', '0.0000', NULL, '2024-01-12 00:00:00', '2024-01-12 00:00:00')
```

The user in question isn't yet on the subscription cycle so there is no record with `["cashier::order_item.cycle"]`.

**Comment by jeroenrosendaal** [comment]
Hi @sandervanhooft. The problem is solved. We have added some subscriptions manually in the past that causes these errors. We removed the old records and now is working fine. Thanks for your time!

**Comment by sandervanhooft** [comment]
Great, thanks for following up! Enjoy!
