### ISSUE TITLE
Getting plan interval 

### ISSUE THREAD

**Issue by PabloHendriks** [mollie/laravel-cashier-mollie#222]
Hi, 

My problem is about getting the plan interval. When looking at the DefaultIntervalGenerator, the interval is a protected attribute and there is only a `isMonthly()` method which would not make distinctions between a monthly subscription or a 3-month subscription. Same thing with a yearly or 2 yearly subscription.

Thanks in advance.

**Comment by Naoray** [comment]
Hi @PabloHendriks,

thank you for your contribution to the codebase.

Before I merge your PR I want to make sure that there isn't another way for your specific use case.

What exactly is your use case? What does your `cashier_plans.php` config file look like? Couldn't you get the information from there?

**Comment by PabloHendriks** [comment]
Hi @Naoray, 

Thank you very much for your quick reply.

Yes, I could use the config to access the interval, though it would be nice to way of accessing the interval from the object itself. I believe that a more 'dynamic' way of accessing it would be more interesting.

Let me know what you think!

**Comment by sandervanhooft** [comment]
Hi @PabloHendriks,

I am not entirely convinced yet, but we're keeping this open for review for the next major release.
