### ISSUE TITLE
Saving custom data on a subscription model

### ISSUE THREAD

**Issue by YouneselBarnoussi** [mollie/laravel-cashier-mollie#224]
Hey,

I currently have a custom subscription model which extends the Cashier model. The only thing I added was a couple of extra columns in the database. Now at the moment what I have to do when creating a subscription is firstly create the subscription and afterwards update it. 

But this means that in the 'SubscriptionStarted' event I won't have access to 'my_custom_data'. I was thinking of adding a fourth parameter specifically for the 'newSubscriptionForMandateId' that gets merged into the `makeSubscription` default array. I already have that working and it works perfectly fine.

For example: 

```php
$subscription = $user->newSubscriptionForMandateId(
    $user->mollie_mandate_id,
    'default',
    $plan,
    ['my_custom_data' => 'wow'], // My implementation
)->create();

// The implementation before.
$subscription->update([
    'my_custom_data' => 'wow',
]);
```

I want to implement something similar for 'newSubscriptionViaMollieCheckout' for full support. For this method, I see that there is already a 'firstPaymentOptions' parameter available but this isn't for saving anything specific data after the payment has been paid. Next, I thought about overriding the metadata (in my app) and merging all the metadata into the 'Subscription' model (in the package) but this might break existing applications.

I am not sure how to get the data from the first payment to the subscription. Do you know how to implement this? If you could point me in the right direction, I am fully willing to implement and test it and open a PR.

Thanks in advance.

**Comment by sandervanhooft** [comment]
I think listening for an event and then updating the subscription record is the way to go here. I'd recommend listening for `OrderInvoiceAvailable`
