### ISSUE TITLE
Question: One time subscription and limited payment methods for plan possible?

### ISSUE THREAD

**Issue by peXed** [mollie/laravel-cashier-mollie#226]
Hello!

Unfortunately, I couldn't find anything in the documentation, and I have two questions. Is it possible to add a subscription plan that won't be auto-renewed? Or do we have to create the plan and then immediately cancel it and prevent the user from renewing the subscription?

Another question we have is: is it possible to limit the payment method for a certain subscription plan (e.g., only allow credit cards)? If so, how?

Thank you very much!

**Comment by sandervanhooft** [comment]
Hi!

Regarding point one: this is not supported out of the box. From your use case description, I'd consider using one off charges instead.

Regarding point 2 (payment method): you can set this on the cashier_plans config file. On the charges (ChargeBuilder) this is not available yet, let me know if you need it or want to contribute a PR.
