### ISSUE TITLE
For one payment multiple orders are being emitted

### ISSUE THREAD

**Issue by GunniBusch** [mollie/laravel-cashier-mollie#227]
if I place a subscription order, then in the database I find multiple subscriptions and orders for each payment. And I see that his is also so that it generates new orders/subscriptions in a interval.

**Comment by sandervanhooft** [comment]
Hi!

Can you please share more information so we may reproduce the issue?
- a code sample that we can test
- the installed cashier package version
- your cashier config files
- any default behavior overrides (i.e. custom models)
- any packages that may collide with Cashier Mollie’s behavior?

Given the above, what exact behavior were you expecting? And what behavior are you seeing?

**Comment by GunniBusch** [comment]
Resolved

**Comment by sandervanhooft** [comment]
Thanks for following up. Enjoy!
