### ISSUE TITLE
Coupon with 100% discount create a loop in mollie checkout

### ISSUE THREAD

**Issue by peXed** [mollie/laravel-cashier-mollie#230]
Hello!

We have the following problem when testing on the live API with a coupon that has a discount fo 100%.

As soon as we want to pay (we testet it with PayPal) everything works on the PayPal site, however as soon as we getting redirected back to Mollie, the screen where we can choose the payment method appears again, but in the background, everything gets setup correctly.
What I didn't test is what will happen, when I put in my payment details again or choose a different payment method the second time I see the screen.

Is that a known problem and if so, is it on Mollies side or the cashier side? Is there a fix?

**Comment by Naoray** [comment]
Hi @peXed,

thanks for reporting your issue!

Can you provide me with the exact configuration you have in `cashier`, `cashier_coupons` and `cashier_plans` and also provide me with the code you used to get this result?

Also how did you test the integration with PayPal exactly? I might be wrong, but creating payments in testmode for me always creates a redirect link to a page where I can only insert credit card details, hence I couldn't test your use case.
