### ISSUE TITLE
Create Custom Plan On The Fly

### ISSUE THREAD

**Issue by DevelopmentNightmare** [mollie/laravel-cashier-mollie#232]
As of now, I don't see any way to create a custom plan on the fly. Not all of my customers have the same amount that they have to pay each month and it's to much to put it all in the config/cashier_plans.php. Is there any way to work around this?

**Comment by sandervanhooft** [comment]
Hi @DevelopmentNightmare ,

You could use a database plan repository to achieve this. More information here:

https://www.cashiermollie.com/12-faq.html#how-can-i-load-coupons-and-or-plans-from-the-database

**Comment by DevelopmentNightmare** [comment]
I feel like there is a lot of information missing, as I always get the "Plan not found" error. Is there a simple how-to on how to implement this? I can't imagine why it has to be so difficult.

**Comment by Naoray** [comment]
Hi @DevelopmentNightmare,

you are right, the process of creating a plan repository should be better documented. I've updated the [documentation](https://www.cashiermollie.com/12-faq.html#how-can-i-load-coupons-and-or-plans-from-the-database) with a more precise example.

Here is the step by step you can take to load your plans from the DB

Create a `DatabasePlanRepository` that implements `PlanRepository` of Cashier.

```php
<?php

namespace App;

use App\Models\Plan;
use Laravel\Cashier\Exceptions\PlanNotFoundException;
use Laravel\Cashier\Plan\Contracts\Plan as PlanContract;
use Laravel\Cashier\Plan\Contracts\PlanRepository;

class DatabasePlanRepository implements PlanRepository
{
    public static function find(string $name): PlanContract
    {
        /** @var Plan $plan */
        $plan = Plan::where('name', $name)->firstOrFail();

        return $plan->buildCashierPlan();
    }

    public static function findOrFail(string $name): PlanContract
    {
        if (($result = self::find($name)) === null) {
            throw new PlanNotFoundException;
        }

        return $result;
    }
}
```

Next, create a `Plan` Model, along with DB migration and Factory (optional). The `Plan` Model can either implement `Laravel\Cashier\Plan\Contracts\Plan` or you can create a dedicated method which returns a cashier `Laravel\Cashier\Plan\Plan` object.

*Note*: In the example we use a method `buildCashierPlan()` to return the Cashier `PLan` object.

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravel\Cashier\Cashier;
use Laravel\Cashier\Plan\Plan as CashierPlan;
use Money\Currency;
use Money\Money;
use Laravel\Cashier\Order\OrderItemPreprocessorCollection as Preprocessors;

class Plan extends Model
{
    use HasFactory;

    /**
     * Builds a Cashier plan from the current model.
     *
     * @returns \Laravel\Cashier\Plan\Plan
     */
    public function buildCashierPlan(): CashierPlan
    {
        $plan = new CashierPlan($this->name);

        return $plan->setAmount($this->getAmount())
            ->setInterval($this->interval)
            ->setDescription($this->description)
            ->setFirstPaymentMethod(config('cashier.first_payment.method'))
            ->setFirstPaymentAmount($this->getAmount())
            ->setFirstPaymentDescription($this->description)
            ->setFirstPaymentRedirectUrl(route('plans-payment.success', ['plan' => $this->id]))
            ->setFirstPaymentWebhookUrl(Cashier::firstPaymentWebhookUrl())
            ->setOrderItemPreprocessors(Preprocessors::fromArray(config('cashier_plans.defaults.order_item_preprocessors')));
    }

    private function getAmount(): Money
    {
        return new Money($this->price, new Currency($this->currency));
    }
}
```

```php
// schema
Schema::create('plans', function (Blueprint $table) {
	$table->id();
	$table->string('name');
	$table->string('description');
	$table->string('price');
	$table->string('currency');
	$table->string('interval');
	$table->timestamps();
});

// factory
return [
	'name' => $this->faker->name,
	'description' => $this->faker->sentence,
	'price' => '10.00',
	'currency' => $this->faker->currencyCode,
	'interval' => '1 month',
];
```

Finally, you can register your custom `DatabasePlanRepository` by binding it to the `PlanRepository` contract within the `AppServiceProvider`.

```php
<?php

namespace App\Providers;

use App\DatabasePlanRepository;
use Illuminate\Support\ServiceProvider;
use Laravel\Cashier\Plan\Contracts\PlanRepository;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        $this
	        ->app
	        ->bind(PlanRepository::class, DatabasePlanRepository::class);
    }
}

```

If you want to test if your setup works, you can execute the following code snippet:

```php
use Laravel\Cashier\Plan\Contracts\PlanRepository;
use App\Models\Plan;
  
Plan::factory()->create(["name" => "test"]);
resolve(PlanRepository::class)->find("test");
```

---

I hope this answers all your questions! If you are still missing some information, please let me know!

**Comment by DevelopmentNightmare** [comment]
Thanks for your help @Naoray! This seems to do the trick!

**Comment by Naoray** [comment]
@DevelopmentNightmare just a follow up:

I noticed that the `getAmount()` method should be rewritten, otherwise the `Money` class returns the € amount in cents rather than in the expected €. To clarify here is an example: `(new Money('10.00', new Currency('EUR')))->getAmount()` returns `10`, but this is 10 Cents. So either pass in the price value times 100 or use the `decimal_to_money()` helper method from this package.

```php
private function getAmount(): Money
{
    return decimal_to_money($this->price, $this->currency);
}
```
