### ISSUE TITLE
Invoice set date format

### ISSUE THREAD

**Issue by GunniBusch** [mollie/laravel-cashier-mollie#236]
Would it be possible to set the date format of the invoice via a configuration entry? 
Now it is hardcoded, and not 100% ideal for other customers in other countries.

**Comment by GunniBusch** [comment]
Created a PR #237 that uses the localization feature of Carbon

**Comment by sandervanhooft** [comment]
Hi @GunniBusch,

I noticed you closed the PR. Is this issue still relevant?

**Comment by sandervanhooft** [comment]
Hi @GunniBusch ,

Thanks for following up.

Forking obviously is a fine approach. Alternatively you could override the provided cashier models with your own. That way you benefit from receiving updates from the this official repo. Either way is fine. Enjoy!
