### ISSUE TITLE
Translations are sometimes not working

### ISSUE THREAD

**Issue by voicecode-bv** [mollie/laravel-cashier-mollie#238]
Hi there, 

We're haunted with an issue where the translations are occasionally not being respected. 

We support 3 languages, NL, EN and FR.

I can confirm that for each language there's a payment.php file in the correct lang folder and in that file there's a description entry:

```
'description' => 'Order: number',
```

Narrowing it down, it seems like this happens when a user swaps a plan. 

<img width="1229" alt="Screenshot 2024-04-17 at 13 16 05" src="https://github.com/mollie/laravel-cashier-mollie/assets/4598259/1a971dae-ce8c-4bde-933d-f13232e7d18f">

<img width="1194" alt="Screenshot 2024-04-17 at 13 08 04" src="https://github.com/mollie/laravel-cashier-mollie/assets/4598259/1a4ba2d2-d374-41f1-b1c7-7d92db592532">

**Comment by voicecode-bv** [comment]
I'm sorry, I think we needed to add some configuration on our end. Closing this one.

**Comment by voicecode-bv** [comment]
Hi @sandervanhooft 

I think its something on our end. I just read about publishing the /lang/vendor/cashier translations and adding the getLocale() method to the, in my case, User model.

I initially thought putting the translations in /lang/en/payment.php would be sufficient.

I've pushed the translations now so we'll see if that solves the issue.

**Comment by Naoray** [comment]
Hi @voicecode-bv,

yes, you are right. To override package translations you have to put the translation into `lang/vendor/{package}/{locale}`.

S. [laravel documentation](https://laravel.com/docs/11.x/localization#overriding-package-language-files) for more details
