### ISSUE TITLE
Retry failed payments via mollie checkout

### ISSUE THREAD

**Issue by ignaciocunado** [mollie/laravel-cashier-mollie#246]
I was referred by Sander to this repository.

## Expected Behavior

When a payment fails, the mandate is automatically canceled. It would be nice if users could retry the failed payment via the checkout page, and, for example change their payment method.

## Current Behavior

Currently, there exists no way for users to go through the checkout to retry a failed payment.

## Possible Solution

A possible solution could be to add a method which redirects the user to the checkout page, and pays for the failed order.

## Context

Sometimes our users' banks reject the payment multiple times, and it would be easier for them and for us to retry payments via the checkout.

As clarification, we would like users to go through this page (see attached screenshot) when a payment fails.
<img width="1512" alt="Screenshot 2024-06-17 at 10 01 16" src="https://github.com/mollie/laravel-cashier-mollie/assets/116840139/1bdb4b63-8f1e-4854-9b70-6624f563e705">

**Comment by sandervanhooft** [comment]
Hi @ignaciocunado ,

This package actually does offer a way to retry failed payments:

https://www.cashiermollie.com/14-retry.html#subscriptions-and-failed-payments

It does however cancel the subscription immediately when a payment fails.
