### ISSUE TITLE
Duplicated verification emails while using this package

### ISSUE THREAD

**Issue by andrasszommer** [mollie/laravel-cashier-mollie#247]
When we use this package under Laravel 11.x, we have noticed the error that every email verification email, after registration is sent twice.

## Expected Behavior
Each email verification email should be sent only once.

## Possible Solution
We managed to track down the source of the error, which is the [EventServiceProvider](https://github.com/mollie/laravel-cashier-mollie/blob/main/src/EventServiceProvider.php) of the package.
The EventServiceProvicer is extending from the original `Illuminate\Foundation\Support\Providers\EventServiceProvider`, which is registering once again the `configureEmailVerification` emails. 
Check the original [EventServiceProvider here.](https://github.com/laravel/framework/blob/6c0561caeb8265b7d17cabeea0ec7d4c5cca28aa/src/Illuminate/Foundation/Support/Providers/EventServiceProvider.php#L74-L76)

This function force pushes the Registered method again to the $listen array:
```php
if (! isset($this->listen[Registered::class]) ||
    ! in_array(SendEmailVerificationNotification::class, Arr::wrap($this->listen[Registered::class]))) {
    Event::listen(Registered::class, SendEmailVerificationNotification::class)
}
```

To fix this issue I recommend updating the `register` method in the EventServiceProvider, without "configuring" the email verification again.

## Possible Implementation
```php
public function register(): void
{
    $this->booting(function () {
        $events = $this->getEvents();

        foreach ($events as $event => $listeners) {
            foreach (array_unique($listeners, SORT_REGULAR) as $listener) {
                Event::listen($event, $listener);
            }
        }

        foreach ($this->subscribe as $subscriber) {
            Event::subscribe($subscriber);
        }

        foreach ($this->observers as $model => $observers) {
            $model::observe($observers);
        }
    });
}
```

## Steps to Reproduce
1. Use Laravel 11.x
2. Users should implement MustVerifyEmail interface and use  MustVerifyEmail trait
3. Create a new user registration
4. Two verification email will be sent for the newly registered user.

Please check whether you also have this error.

**Comment by sandervanhooft** [comment]
I haven't verified the behavior yet but prepared a patch here anyway: #248 . Can you give it a try @andrasszommer ?

**Comment by sandervanhooft** [comment]
Fix released! Thank you @andrasszommer

**Comment by sandervanhooft** [comment]
https://github.com/mollie/laravel-cashier-mollie/releases/tag/v2.13.0
