### ISSUE TITLE
nextPaymentAt doesn't work

### ISSUE THREAD

**Issue by jpmannee** [mollie/laravel-cashier-mollie#25]
I'm creating a subscription for a first payment like this:

$result = $user->newSubscription($name, $plan)
    ->quantity($quantity)
    ->nextPaymentAt($nextPayment)
    ->create();

The quantity is set to the passed $quantity variable, so that works.

The subscription has a period of 3 months and the $nextPayment variable is 2 months in the future.
I expect the upcoming payment for the created subscription to be scheduled on the passed $nextPayment variable.
But the upcoming payment is scheduled on 3 months in the future as if nextPayment was not used?

I also noticed that in the createFromPayload method in Laravel\Cashier\FirstPayment\Actions\StartSubscription nothing is done with 'nextPaymentAt'. So even if 'nextPaymentAt' is in the payload, nothing is done with it. Shouldn't it be handled in there?

**Comment by jpmannee** [comment]
Hi Sander and/or ciungulete, 

is there any update on this issue?

Thanks,
JP

**Comment by sandervanhooft** [comment]
Looking into it. First guess is that this should only be available on mandated payments, not on the first payment / starting a new subscription without (valid) mandate.

**Comment by ciungulete** [comment]
Hi @jpmannee,

We solve it https://github.com/mollie/laravel-cashier-mollie/pull/42

**Comment by sandervanhooft** [comment]
Here's the release: https://github.com/mollie/laravel-cashier-mollie/releases/tag/v2.0.7

Enjoy!
