### ISSUE TITLE
Change plan price and coupon rules does not work for existing subscriptions

### ISSUE THREAD

**Issue by Tailchakra** [mollie/laravel-cashier-mollie#253]
When there's already a client with a subscription and applied coupon I can't change the subscription price and coupon quantity.

I have a coupons and subscriptions table in my database and I have clients that already have a subscription with an applied coupon. I however want the coupon to be able to be used for 240 cycles and the subscription price raised. Changing times_left in redeemed_coupons and the subscription price in "plans" however did not work. The next cycle simply starts with the old values.

Is there any cache that needs to be cleared between Mollie and our software, or am I missing something? Shouldn't changing the values 'simply' change the rules for the next cycle?

If I create a new subscription it works perfectly with the new prices, it's solely the existing subscriptions that do not follow the new prices but instead keep its old price.

![image](https://github.com/mollie/laravel-cashier-mollie/assets/24505478/ede8f453-6c89-4fff-802a-31d967d3d436)
![image](https://github.com/mollie/laravel-cashier-mollie/assets/24505478/5d3a21de-b7da-4379-a328-7b5cada01311)
![image](https://github.com/mollie/laravel-cashier-mollie/assets/24505478/88c8655f-3c76-4690-b7b0-54934afb916e)

**Comment by sandervanhooft** [comment]
Hi @Tailchakra ,

The data looks correct to me. The coupons are applied dynamically at the last possible moment: when the subscription cycle gets renewed and the definite Mollie payment amount gets calculated.

This way we also see the full tally (subscription order item + coupon order item) with correct numbers on the resulting order and invoice.

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
