### ISSUE TITLE
Getter for if a user is subscribed

### ISSUE THREAD

**Issue by ignaciocunado** [mollie/laravel-cashier-mollie#261]
It would be nice to have a getter on the `Billable` trait that returns true if a user is subscribed (to anything). Similar to 
```php
public function subscribed($subscription = 'default', $plan = null)
```

but it would return true if a user has **any** active subscription.

**Comment by sandervanhooft** [comment]
Hi @ignaciocunado ,

Thanks for this ticket. I agree with the use case, not sure about the implementation yet. We'll look into it.

**Comment by ignaciocunado** [comment]
Thanks. Do let me know if you would like me to change something.
