### ISSUE TITLE
Send payment links to customers

### ISSUE THREAD

**Issue by ignaciocunado** [mollie/laravel-cashier-mollie#268]
Good afternoon,

We are implementing a feature where we want:

An admin, through an admin panel, creates a Charge for a user. However, even if we have a valid mandate for this user, we do not want to charge him without his consent. Therefore, we want to use the ```newFirstPaymentChargeThroughCheckout``` method. This will create a redirect link for the user to the Mollie checkout page.

Since the charge is created through an admin panel, how can we allow the user to pay for this charge when they log into their account? I see that payments expire after 15 minutes and did not see an obvious way to override this.

**Comment by ignaciocunado** [comment]
I guess a payment link can be sent to the customer, but is it possible to associate that to an order and automatically get an invoice?

**Comment by sandervanhooft** [comment]
Hi @ignaciocunado ,

I'd suggest to create your own Payment Link feature, then when the client visits that start the cashier payment you envisioned. This way you're fully in control and are not hampered by any Mollie payment expirations.

**Comment by sandervanhooft** [comment]
I hope this helps, feel free to reach out here otherwise.
