### ISSUE TITLE
Subscriptions without mandate

### ISSUE THREAD

**Issue by simonblok-t100** [mollie/laravel-cashier-mollie#270]
Hello. Thanks for this great package; it works straight out of the box and is very flexible in most parts.

However, we have a use case for this package where subscriptions (licenses) can also be purchased by manual payment via paymentlinks. So the subscription is started and the user should receive an invoice that should be paid in, let's say, 14 days; if after that date nothing is paid, the subscription will be canceled. 

How can I handle this use case? I see in the Stripe Laravel Cashier documentation something like this is possible with the `CreateAndSendInvoice method` at making the subscription ([docs](https://laravel.com/docs/11.x/billing#collecting-recurring-payments-via-invoice-emails)). But this is missing in this Mollie version (of course, because of the nature of this package)

As an alternative, I can just add another 'UserLicense' layer between the user and the Cashier subscription, but I want to keep things as simple as possible.

**Comment by sandervanhooft** [comment]
Hi @simonblok-t100,

Thank you for the kind words.

At first glance I'd say this is tricky to bolt on to the existing subscription features of this package. It's probably easier to handle the payment logic for this very specific use case outside of Mollie Cashier.
