### ISSUE TITLE
Object of class Money\Money could not be converted to int on /webhooks/mollie/aftercare

### ISSUE THREAD

**Issue by marijnbent** [mollie/laravel-cashier-mollie#29]
The entire error:
https://flareapp.io/share/Lm8EKbjP#F51

```php
if ($molliePayment && $molliePayment->hasChargebacks()) {

            $localPayment = Payment::findByPaymentId($molliePayment->id);

          // the line the exception occurs
            if ($localPayment->amount_charged_back < mollie_object_to_money($molliePayment->amountChargedBack)) {
                $localPayment->amount_charged_back = mollie_object_to_money($molliePayment->amountChargedBack);
                $localPayment->save();

                Event::dispatch(new ChargebackReceived($localPayment, $molliePayment->amountChargedBack - $localPayment->amount_charged_back));
            }

        }
```

The value of the payment id for both amount_refunded as for amount_charged_back in the database is 0.

**Comment by magosla** [comment]
I also encountered the same issue 
```ErrorException Object of class Money\Money could not be converted to int 
    vendor/mollie/laravel-cashier-mollie/src/Http/Controllers/AftercareWebhookController.php:37 Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    vendor/mollie/laravel-cashier-mollie/src/Http/Controllers/AftercareWebhookController.php:37 Laravel\Cashier\Http\Controllers\AftercareWebhookController::handleWebhook
    vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:48 Illuminate\Routing\ControllerDispatcher::dispatch
    vendor/laravel/framework/src/Illuminate/Routing/Route.php:262 Illuminate\Routing\Route::runController
    vendor/laravel/framework/src/Illuminate/Routing/Route.php:205 Illuminate\Routing\Route::run
    vendor/laravel/framework/src/Illuminate/Routing/Router.php:695 Illuminate\Routing\Router::Illuminate\Routing\{closure}

**Comment by Mul-tiMedia** [comment]
I have created a pull request to address this problem. @sandervanhooft  can you merge this? 
We also encountered the same problem in production.

**Comment by ciungulete** [comment]
I think we can close this. Let me know if it should be reopened.

**Comment by sandervanhooft** [comment]
Thanks for reporting this! A fix has just been released in [2.0.3](https://github.com/mollie/laravel-cashier-mollie/releases/tag/v2.0.3).

Thanks @Mul-tiMedia for the patch!

**Comment by Mul-tiMedia** [comment]
@ciungulete @sandervanhooft this one can not be closed, i overlooked something.
https://github.com/mollie/laravel-cashier-mollie/blob/1dd0b88caa43b1580756201b313932edee5a2e87/src/Http/Controllers/AftercareWebhookController.php#L41
See above line, this is now giving an error `Unsupported operand types: stdClass - int`

I think the fix would be: 
```
Event::dispatch(new ChargebackReceived($localPayment, mollie_object_to_money($molliePayment->amountChargedBack)->subtract($localPayment->getAmountChargedBack())));
```

Except i don't like the length of the string. I did go ahead and already created an extra pull request to fix this.
https://github.com/mollie/laravel-cashier-mollie/pull/32

I'm not 100% certain, this is the preferred outcome, so if anyone would like to take a look at it :)

**Comment by sandervanhooft** [comment]
I'm on the road right now, I'll take a look tomorrow. @ciungulete feel free to beat me to it 😄

**Comment by sandervanhooft** [comment]
I've just verified this patch works, preparing release patch now.

**Comment by sandervanhooft** [comment]
All done! 🚀 

https://github.com/mollie/laravel-cashier-mollie/releases/tag/v2.0.4

Enjoy!
