### ISSUE TITLE
How do I find the user in event listeners?

### ISSUE THREAD

**Issue by wouterdorgelo** [mollie/laravel-cashier-mollie#3]
Using listeners I want to log all events in a database.

Here is an example of my `LogFirstPaymentPaid` listener:

```
<?php

namespace App\Listeners;

use App\Models\Log;
use App\Models\User;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Laravel\Cashier\Events\FirstPaymentPaid;

class LogFirstPaymentPaid
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  FirstPaymentPaid  $event
     * @return void
     */
    public function handle(FirstPaymentPaid $event)
    {
        $user = User::findOrFail( $event->???? );

        Log::create([
            'user_id' => $user->id,
            'message' => 'First payment paid'
        ]);
    }
}
```

How do I get the current user in my `handle()` method from the `$event`? I remember from a tutorial that using `Auth::user()` is a bad idea when queueing event listeners.

**Comment by pepijndik** [comment]
HI check 
https://github.com/mollie/laravel-cashier-mollie/blob/ef84f1003a0596f028caf6eda1ce19f2373025de/src/Events/FirstPaymentPaid.php
the event class, in here you can see that there are two main public objects available payment and order 

[FirstPayment/FirstPaymentBuilder.php ](https://github.com/mollie/laravel-cashier-mollie/blob/ef84f1003a0596f028caf6eda1ce19f2373025de/src/FirstPayment/FirstPaymentBuilder.php)
than take a look  at the first payments builder and there you can see that the $this->payments->owner is the billable model that's used by the billable trait.

so if you wanted to  notify this customer/user there first payment is a success you can use this
$this->payments->owner 
I gues this is how you can do this out of my head :-)
