### ISSUE TITLE
First Payment, with existing mandate redirects to mollie

### ISSUE THREAD

**Issue by Mul-tiMedia** [mollie/laravel-cashier-mollie#34]
Just want to verify this logic, because in v1 this logic was working different from now in v2.

Example v1:
1. Create mandate without laravel cashier upfront. 
2. start newSubscription()->create();
3. Subscription created and transaction started within mollie by directdebit (through cashier:run)

Example v2:
1. Create mandate without laravel cashier upfront. 
2. start newSubscription()->create();
3. No subscription created, payment started. Redirects to mollie checkout page. 

I looked up what the difference is between v1 & v2 and that's if have to set in `cashier.php` config underneath: `first_payment` the `method` to `directdebit` Now it's actually creating a new subscription without redirecting to mollie checkout. 

I could not find anything within the documentation about this, and i think the method for `first_payment.method` should not be `directdebit` it feels wrong.

**Comment by sandervanhooft** [comment]
Hi @Mul-tiMedia,

Without valid mandate cashier will not create a new subscription without going through Mollie's checkout. Once the payment reaches status paid, Cashier's webhook gets called, and then the Subscription is created. That behaviour has not changed between v1 and v2, except for that the Payments are now also tracked in db.

1. What do you get when you run `$billable->validateMollieMandate()`?

1. Please try a supported _first_ payment method. _directdebit_ is not supported ([source].(https://docs.mollie.com/payments/recurring#payments-recurring-first-payment)) <img width="780" alt="image" src="https://user-images.githubusercontent.com/7265703/147271051-e23f71ca-f455-470f-9d94-c2cc25fdb190.png"> Note that a number of first payment methods like `ideal` result in a `directdebit` mandate, but `directdebit` cannot be used to instantiate a first payment.

1. For debugging, try using `$billable->newSubscriptionForMandateId($billable->mollie_mandate_id, $subscription, $plan);` directly. ([link](https://github.com/mollie/laravel-cashier-mollie/blob/741f51b035e77461fc7e16168ad548404c0732be/src/Billable.php#L86))

**Comment by Mul-tiMedia** [comment]
Hi @sandervanhooft 

I understand your reply, except our workflow is different than you wrote about.
We create a valid mandate without laravel cashier. We do this by calling api calls to mollie directly. Because we dont want our customers to make a first payment of a few cents. We let our customer check a box and then we create a valid mandate upfront. 

Then the situation is as following: We have a **valid** mandate. Then a customer wants to start a new subscription. Even though the customer has this valid mandate Cashier still wants to redirect to mollie to make a first payment. 

Cashier v1 does not redirect, v2 does redirect. The difference between cashier v1 and v2 is as following:

In v2 the following line has been added:
https://github.com/mollie/laravel-cashier-mollie/blob/741f51b035e77461fc7e16168ad548404c0732be/src/Billable.php#L78

This line of code checks the firstPaymentMethod from the config file. Except there should only be ideal creditcard or paypal or such.. 

In v1 the code was as following:
https://github.com/mollie/laravel-cashier-mollie/blob/6acdadc69b00bde337c37a10b6e2f1838ac93217/src/Billable.php#L75

I hope you understand my question now. :)

**Comment by sandervanhooft** [comment]
I understand the use case, but I think `MandateMethod:: getForFirstPaymentMethod()` should throw an exception when passed `directdebit`, because that is not a valid first payment method. Fixing that will avoid a lot of confusion.

**Comment by Mul-tiMedia** [comment]
@sandervanhooft  i agree, directdebit should not be passed as the first payment option.
But in our case i have to do it to pass the if else statement:
https://github.com/mollie/laravel-cashier-mollie/blob/741f51b035e77461fc7e16168ad548404c0732be/src/Billable.php#L84

![Screenshot 2021-12-24 at 11 20 46](https://user-images.githubusercontent.com/12711809/147344519-0b0c240d-7dc4-4dc8-a52f-4853c38e3e11.png)
See our screenshot for verifying our mandate is valid. So will always be redirected to mollie because the L84 blocks because it cannot find a correct payment method even though my mandate is valid.

**Comment by Mul-tiMedia** [comment]
So i did some digging. And i think this issue can be closed. 

Except, i think we should add a paragraph to the documentation part of upgrading from v1 to v2.
That if you are creating your own valid mandates upfront without cashier, you have to set the `cashier.first_payment.method` to a valid payment method. Like `ideal` or `creditcard`. 
Because it's default set to `null` (empty array). And therefore it will not pass the if statement as written in my comment above.

I you do this, and a valid mandate was detected cashier will start a new subscription without actually redirecting you to this firstPaymentMethod.

**Comment by sandervanhooft** [comment]
Thanks for following up!

Manually setting the mandate is not officially supported by Cashier (v1 nor v2), so it would only be confusing to include it in the upgrade documentation. I'll keep an eye out to see if we need to detail it somewhere else.
