### ISSUE TITLE
User is credited for full plan value on swap instead of firstPaymentAmount

### ISSUE THREAD

**Issue by vdBergMike** [mollie/laravel-cashier-mollie#35]
We are using Laravel Cashier Mollie for our project but running into some trouble with a quite unique use-case.

1. A new User is offered 2 paid plans, both with a FirstPaymentAmount to get a mandate and to provide our new User with a discount for the trial-period.
2. Once the Subscription is activated, a user gets the possibility to swap to a next plan (because a plan corresponds with credits and we want to give immediate access to these extra options).
3. The Subscription is swapped, but the User is credited not the FirstPaymentAmount, but a value based on the ratio of the default value of a Subscription.

**Example**
User chooses Plan A: 
- 25,00 per month, 
- firstPaymentAmount: 12,50 

User upgrades to Plan B:
- 50,00 per month,
- gets refunded the ration based on 25,00 instead of 12,50.

The User should be credited a ration of 12,50 instead of a ration of 25,00.
(because in this case we will lose money)

Is there any way to achieve this?

**Comment by sandervanhooft** [comment]
Is using a generic trial an option?

https://www.cashiermollie.com/03-trials.html#without-mandate-upfront

**Comment by sandervanhooft** [comment]
Anyway, nice edge case / find. I have to double check this.

Can you confirm that you were expecting the following behavior:

_when swapping plans during a trial, no prorating and no credits should be applied to the billable's account._

**Comment by vdBergMike** [comment]
Hi Sander, thanks for your fast response!

I can confirm the behaviour:
"when swapping plans during a trial, no prorating and no credits should be applied to the billable's account."
But we use the trial in a different way (perhaps incorrectly).

**To clarify my use-case and what we want to achieve:**
We would love to offer our users a one-time discount. Currently we use the `->trialUntil()` because we want to trigger the FirstPaymentAmount of a subscription (which is the discount price).

On upgrade, we cancel the trial, with `->skipTrial()->swap($next_plan)` because we want the plan-features to be instantly available. At that moment, the plan is switched correctly, but a prorating is applied to the "plan->amount", instead of the FirstPaymentAmount.

This seems to be the correct behaviour. 

**Other use-case we tried:**
We tried to create a subscription with a coupon, to get to the discount price.
But in that case, the same happens:

- The User gets a subscription (with discount), mandate etc. is working perfectly as expectedd.
- If the User swaps to another plan, the prorating is also for the "plan->amount", instead of the paid value (with the coupon code).

In both examples, a user will get more credits then the User actually paid. 
for example: 

Plan price 50 euro. Discount price 25 euro (50% discount). 
If the user upgrades to "pro" (100 euro). The invoice is:

Default plan -50 euro
Pro plan 100 euro
Due: 50.

But the user paid 25 euro, instead of 50 euro.

If it could be possible to add a `->noProrate()` method, or a `->withProrate($value)` method, that will suit our needs.
Because in that case we can detect if a user upgraded the first time, and we can edit the prorating value.

**Comment by sandervanhooft** [comment]
Thanks for the detailed description @vdBergMike ! I'll look into this with the team and get back to you.

**Comment by JelleDamen** [comment]
Hey @sandervanhooft I was wondering if you have any update on this issue :) ?

**Comment by sandervanhooft** [comment]
It's a tricky one. I am still looking into it.

**Comment by sandervanhooft** [comment]
@vdBergMike @ciungulete

How about this approach for enhancing the prorating calculation:

 In essence:

1. Get the most recently paid Order for the Subscription.
2. Then, take the `unit_price` of this specific Subscription's OrderItem.
3. MINUS any Coupons applied to this specific Subscription in the same Order. Meaning: Coupons generate additional OrderItems on the Order - subtract these items `unit_price`.
4. The resulting amount should be the input for the prorating.

**Comment by vdBergMike** [comment]
@sandervanhooft 

Thanks for the reply!
This should be the exact expected behaviour or the prorating method. 

In the other hand, shouldn't it be easier to implement the same methods as Laravel Cashier provides out of the box?
(https://laravel.com/docs/8.x/billing#prorations),

Where one can define what type of prorating should be used, if any, or no prorating at all.

**Comment by sandervanhooft** [comment]
Thanks for confirming @vdBergMike !

> In the other hand, shouldn't it be easier to implement the same methods as Laravel Cashier provides out of the box?
> Where one can define what type of prorating should be used, if any, or no prorating at all.

From a design / dev experience perspective: yes. From an implementation perspective: probably not. Maybe on a future major release as I suspect it will involve a breaking change. But feel free to prove me wrong anytime :).

Also note that even if we introduce methods such as `noProrate()`, I'd still consider the behaviour I just described the best default when prorating.

**Comment by vdBergMike** [comment]
Agree on that! Would love to add it as a feature request :)

**Comment by sandervanhooft** [comment]
Hey @vdBergMike,

We went over this again while working on some patches. We noticed this:

> On upgrade, we cancel the trial, with `->skipTrial()->swap($next_plan)` because we want the plan-features to be instantly available. At that moment, the plan is switched correctly, but a prorating is applied to the "plan->amount", instead of the FirstPaymentAmount.

How about `->swap()->skipTrial()` instead (so swapping before ending the trial)? That way there is no prorating applied. Does that solve (part) of your problem?

**Comment by sandervanhooft** [comment]
@vdBergMike can you elaborate on my previous comment?

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.

**Comment by sandervanhooft** [comment]
@vdBergMike This PR improves the reimbursement calculation: #61 .

**Comment by codebolt-mike** [comment]
@sandervanhooft just a heads-up;

We managed to fix this issue, using one-time charges on upgrades (during trial periods)
(where we charge a user the difference between the $current_plan->first_time_amoiunt vs. $plan->first_time_amoiunt).

For downgrades, we add the difference of the plans as a negative balance of credits. 

We might be able to fix this with the ```false``` flag on ->swap() for sending invoices.
But for now this works very well in our case.
