### ISSUE TITLE
orders table already exists

### ISSUE THREAD

**Issue by divdax** [mollie/laravel-cashier-mollie#39]
I already have an orders table in my project. Any chance to change the `Order` model table name from this package? Used models should always be defined in a config so we can swap them with our own to customize it.

**Comment by sandervanhooft** [comment]
Currently no. Feel free to submit a PR.

**Comment by nicolaibaaring** [comment]
I just completed changes that solve this issue by making all the models configurable. I will submit a PR soon. 
It doesn't change any existing behavior and current tests are passing. The addition is covered by tests too.
