### ISSUE TITLE
Billable subscriptions method returns all subscriptions

### ISSUE THREAD

**Issue by bartbergmans** [mollie/laravel-cashier-mollie#40]
When I call the `subscriptions()` method in my Billable model (the current logged in user) it returns all the subscription of all the users instead of just the ones belonging to the owner. 

Is this expected behavior and should I make a custom method that only returns the subscriptions that belong to the given Billable?

**Comment by ag84ark** [comment]
Hi @bartbergmans,
I have created a test project with 2 users, each subscribed to the same plan.
When trying to get the subscriptions for each user, I always get just the subscription of that user.

Can you try this code in tinker and see what you get:
```php
use App\Models\User;
$users = User::all();
$users->each(function(User $user){
    dump("Subs for user id #$user->id");
    dump($user->subscriptions->toArray());
});
``` 
also, I tried the code below and got only the user subscription
```php
Auth::loginUsingId(1);
dump(auth()->user()->subscriptions()->get()->toArray());
```
Try to look at the “owner_type” and “owner_id” in the results from the code from above.

If you still have problems, can you please post the code that is generating the problem.

**Comment by bartbergmans** [comment]
Ah.. I'm stupid. I had the following code to get the subscriptions:
```
$member->subscriptions()
                ->where('ends_at', '>=', date('Y-m-d H:i:s'))
                ->orWhere('ends_at', null)
                ->get()
```
The `subscriptions()` call works perfect, but I messed up with the `orWhere()`. 
Thanks a lot for your help, fixed my query and it works now!

**Comment by ag84ark** [comment]
Hi @bartbergmans, very glad to see that you found your problem. 
It happens to all of us, things like this. Glad I could help a little.
