### ISSUE TITLE
Feature request: Add payment details on renewal webhook

### ISSUE THREAD

**Issue by voicecode-bv** [mollie/laravel-cashier-mollie#41]
Hi there, 

As I'm implementing this package in my project, I noticed the FirstPaymentPaid and OrderPaymentPaid payloads are different. 

When handling a FirstPaymentPaid event, there's a payment object found in the event payload. It seems like it's missing in the OrderPaymentPaid event payload. This is very useful to have, especially when using multi currency as Mollie would return a settlementAmount object, which contains the converted EUR value. We need this value to create invoices in Exact.

Now it seems like when I receive an OrderPaymentPaid event, an additional API request is necessary to fetch payment details manually.

```
{
    "payment": {
        "resource": "payment",
        "id": "***",
        "mode": "test",
        "amount": {
            "value": "4.99",
            "currency": "USD"
        },
        "settlementAmount": {
            "value": "4.27",
            "currency": "EUR"
        },
}
```

Maybe I'm missing something, if so, please let me know.

Thanks for providing this package!

Michael

**Comment by sandervanhooft** [comment]
Clear use case, thanks!

The Mollie Payment object on `FirstPaymentPaid` is actually considered to be v1 legacy.

On `OrderPaymentPaid`, it's possible to retrieve the Order. Then, you could do this:

```php
$cashierPayment = $orderPaymentPaidEvent->order->payment;

// Option A
$id = $cashierPayment-> mollie_payment_id;
$molliePayment = mollie()->payments->get($id);

// Option B
$molliePayment = $cashierPayment->order->payment->asMolliePayment();
```

Hope that helps!

If you know of a better way, feel free to suggest/submit a PR.
