### ISSUE TITLE
Can’t determine if a subscription is current

### ISSUE THREAD

**Issue by RicLeP** [mollie/laravel-cashier-mollie#44]
I’ve created a plan like so:

```php
'member' => [
	'amount' => [
		'value' => '20.00',
		'currency' => 'GBP',
	],
	'interval' => [
		'generator' => AdvancedIntervalGenerator::class,
		'value' => 1,
		'period' => 'year',
		'monthOverflow' => true,
	],
	'description' => 'Membership',
]
```

And subscribed a User resulting in:

```
// subscription
"id" => 38
"name" => "membership"
"plan" => "member"
"owner_type" => "App\Models\User"
"owner_id" => 75
"next_plan" => null
"quantity" => 1
"tax_percentage" => "0.0000"
"ends_at" => null                       // is this correct?
"trial_ends_at" => null
"cycle_started_at" => "2022-01-18 12:11:24"
"cycle_ends_at" => "2023-01-18 12:11:24"
"scheduled_order_item_id" => 91
"created_at" => "2022-01-18 12:11:24"
"updated_at" => "2022-01-18 12:11:24"
```

In my index.php I’ve added `\Carbon\Carbon::setTestNow(now()->addYears(3));` to set the application beyond the end of the annual subscription period.

However the subscription is still shown as valid.

```php
echo Auth::user()->subscribed('membership'); // true - expected false
echo Auth::user()->subscription('membership')->active(); // true - expected false
```

```blade
@if (!Auth::user()->subscribed('membership'))
// Does not reach here.
// tell the user their subscription has expired / needs renewing
@endif
```

Have I set something up wrong or am I misunderstanding how the subscription checking works?

**Comment by sandervanhooft** [comment]
The subscription is valid until it's cancelled. Are you maybe thinking of the billing cycle instead? 🤔

**Comment by RicLeP** [comment]
This is for an annual membership. I think I understand how it works now - Mollie will always auto renew the payment by default so there is never any ‘expired’ date. The cancel membership (renewals) the user has to explicitly choose to do so.

In theory I could cancel any memberships that reach their `cycle_ends_at` date and email the user asking if they want to continue their membership if I wanted to be a little less proactive in taking payments. I think it will be using auto-renew though.

**Comment by sandervanhooft** [comment]
It will be expired once the subscription's end_date has passed. This field gets filled when the subscription is cancelled and offers a grace period until the end of the billing cycle during which the subscription is still valid. During this grace period it's still possible to resume the subscription.

This means that for your use case you could proactively cancel the subscription after the payment is received, and ask some time before the ends_at date if they would like to renew ("opt-in").

For most use cases it makes more sense to just let it run automatically instead, and notify the customer a week before he gets billed.

Notifying the customer in advance that you're going to bill them always is a good idea and significantly reduces chargebacks.
