### ISSUE TITLE
Directdebit subscriptions with mandat up front

### ISSUE THREAD

**Issue by tobischulz** [mollie/laravel-cashier-mollie#45]
Hello,

I`m upgrading from v1 and got problems with a manually created directdebit mandat with the mollie api and creating a subscription with that. Handling that like described here: https://github.com/laravel/cashier-mollie/issues/164#issuecomment-598798227

## Mollie API Exception

> Error executing API call (422: Unprocessable Entity): The payment method does not support sequence type. Field: sequenceType. Documentation: https://docs.mollie.com/overview/handling-errors

The **sequenceType** is set to **first** on default i guess.

## How i create a directdebit mandat
![creatingmandat](https://user-images.githubusercontent.com/576014/150978437-28844ce0-207b-446f-aac9-c946e0b65320.png)

## How i create a new subscription
![creatingsubscription](https://user-images.githubusercontent.com/576014/150978445-9adefb81-cecf-42c9-95c7-3a1d8a7299cb.png)

This works fine on v1. What do we have to change to get this to work again in v2? 

Regards and Thanks

**Comment by tobischulz** [comment]
So i updated the config/cashier.php file and added the **directdebit** method to the *first_payment.method* array. After that the payment works and the subscription was successfully created in database. After cashier:run the order was created as well. Am i doing it right? :-)

**Comment by sandervanhooft** [comment]
Hi @tobischulz !

"Geschafft!" Looks like it!
