### ISSUE TITLE
Plans with price per user

### ISSUE THREAD

**Issue by nunofmmarques** [mollie/laravel-cashier-mollie#52]
I'm currently working on a platform that already uses Laravel Cashier Mollie for subscription plans.
But instead of a default plan amount value the users must be able to have specific values.

For example:

- The user A has 100 points and wants to subscribe de plan FOO, the plan price should be for exemple 25.
- The user B has 50 points and also wants to subscribe the FOO plan for for him the price should be 35.

Since the recurring payments uses the default plans value defined in the config/cashier.php this is not possible.

Is there any solution to achieve this?

Thank you very much.

**Comment by sandervanhooft** [comment]
Hi @nunofmmarques,

I think using a custom preprocessor would suit your use case best. You can add one to your plan in config/cashier_plans.

Some implementation details/examples can be found here:

https://github.com/mollie/laravel-cashier-mollie/tree/main/src/Order

It's not extensively documented yet. Essentially a preprocessor takes a collection of pending order items right before they're turned into the definitive order. So you can filter out the order item there and modify the price, or add an additional order item with a discount (negative amount).

**Comment by nunofmmarques** [comment]
Thank you for the response @sandervanhooft !

Instead of modifying the price at that point I need to save the right price at the subscription creation....
Unfortunately i'm not being capable of doing it. Is there any function to do it?

Thank you once again

**Comment by sandervanhooft** [comment]
Another option could be to override the PlanRepository and see if you can customise it to your needs there. But I am not so certain of that route. I'd go with the option in my previous comment.
