### ISSUE TITLE
 Deprecated : Return type of Money\Money::jsonSerialize()

### ISSUE THREAD

**Issue by vollit** [mollie/laravel-cashier-mollie#54]
Hello,

After installing the new version of the package i get this message on PHP 8.1.

Laravel: 8.40
Laravel-cashier-mollie: 2.0
PHP: 8.1

```
Deprecated: Return type of Money\Money::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
```
Does anyone know how to fix this ?

**Comment by sandervanhooft** [comment]
Thanks for reporting @vollit !

This is an issue with moneyphp combined with php 8.1. We'll need to upgrade moneyphp on our end to 4.0.3 to fix this.
