### ISSUE TITLE
Metadata to config.cashier_plans

### ISSUE THREAD

**Issue by pepijn-hockers** [mollie/laravel-cashier-mollie#56]
Is it possible to add metadata such as features to the config.cashier_plans?

**Comment by sandervanhooft** [comment]
Hi! No, sorry, but it isn't. It also would involve a breaking change, so in the current version it will not be added. I'll put it on the list of ideas for v3.

Optionally you can try and override the PlanRepository and return something like a CustomizedPlan, extending the default Plan. And carry the metadata in that CustomizedPlan.

**Comment by pepijn-hockers** [comment]
Thanks for the recommendation and quick answer!
