### ISSUE TITLE
$user->subscribedToPlan('plan_name') does not work

### ISSUE THREAD

**Issue by core45** [mollie/laravel-cashier-mollie#59]
A while ago we where discussing plan swapping. In the discussion in my pull request user ronald184 said:

```
Hi, correct me if i'm wrong, but i don't get why this is changed.
You can check a plan with user()->subscribedToPlan('plan_name'), and check if a user has a subscription with user()->subscribed('subscription_name').
Now you can't have a subscription (product) with different plans as the name will me swapped with the plan on swap (if that makes sense).
```

The thing is that it does not work (or I'm doing something wrong). 
So:

In the DB in subscriptions table I have a record:
id | name | plan | owner_type | owner_id | next_plan | quantity ...
3 | standard | standard | App\Models\User | 3 |NULL | 1 ...

now I'm trying to check the subscription:

$user = User::find(3);

$user->subscribed('standard');                   <- returns TRUE as it should
$user->subscribedToPlan('standard');       <- returns FALSE but this user DO HAVE this plan

Am I doing something wrong here?
And how can I swap the plan and know which plan the user has after swapping?

**Comment by core45** [comment]
Hi guys. Can we address this issue please? I can not swap subscriptions.

**Comment by core45** [comment]
OK i have found what was wrong. 
You have to call this method and not like ronal184 falsely stated but like this $user->subscribedToPlan('standard', 'standard);

**Comment by sandervanhooft** [comment]
👍 Thanks for following up @core45 and clearing this up!
