### ISSUE TITLE
Refunds: order_id or original_order_id??

### ISSUE THREAD

**Issue by JelleVanDerMeulen** [mollie/laravel-cashier-mollie#6]
De refund table has 2 order_id columns. Which one is used? order_id is used in the refunds relation in the Order model. original_order_id is used in the RefundBuilder. Seems like a bug.

**Comment by sandervanhooft** [comment]
Not a bug. A refund is performed on an original order and generates a new credit order.

**Comment by JelleVanDerMeulen** [comment]
It seems like order_id doesn't get filled anywhere. You never get any refunds back form an existing order. There is no relation between order and refund based on the field original_order_id.

**Comment by sandervanhooft** [comment]
The credit order gets created once the refund is processed by Mollie. That can take anywhere between some hours and days.

Also note that Mollie's test mode doesn't support this completely: the refund will not get marked as fully processed but remain pending indefinitely.
