### ISSUE TITLE
Adding order ID to the redirectUrl

### ISSUE THREAD

**Issue by pepijn-hockers** [mollie/laravel-cashier-mollie#60]
![image](https://user-images.githubusercontent.com/85340650/155292603-63b14e73-246a-4e06-a993-f9ef90696dd0.png)

## Problem
I investigated the package because we are considering implementing Mollie. But I didn't found a solution for adding the order ID to the redirectUrl dynamically. I need this feature to make a more pleasant user experience for our customers.

## Desired situation
I want to add the order ID to the redirectUrl. So I can get the referenced order for the customer. This way I can display information about the specific order. 

@sandervanhooft I want to contribute to the package if this feature is desired.

**Comment by sandervanhooft** [comment]
Hi @pepijn-hockers !

You can set the redirectUrl in the config file. And include `{payment_id}` to automatically insert the Mollie payment id there. You can use that to retrieve the related order through the payments table.

I think that's the quickest way to solve your problem.

Another solution would be to implement a similar solution for a {cashier_order_id} and/or {cashier_payment_id}. I'm open to a PR for that 👍.
