### ISSUE TITLE
Call to undefined method App\Models\User::findInvoice()

### ISSUE THREAD

**Issue by vollit** [mollie/laravel-cashier-mollie#62]
I can't find the function findInvoice() in the package. When I call this function on my user model, it gives me this error: 

`[2022-02-25 10:49:48] testing.ERROR: Call to undefined method App\Models\User::findInvoice()`

I've been searching through the package, but can't find where the code is for this function.

In the Billable file there is a function called **downloadInvoice()** but not the **findInvoice()**.

Am I missing something?

**Comment by sandervanhooft** [comment]
You are right! Working on a patch!
