### ISSUE TITLE
Metered billing example

### ISSUE THREAD

**Issue by sha1md5** [mollie/laravel-cashier-mollie#64]
Can anyone provide an example of implementation of metered billing?
We are trying to implement custom subscription where value depends on several user responses.
I tried use preprocessors but seems it doesn't work on first subscription payment.
Even if we modify plan price on the fly and managed get correct first payment on Mollie via config params override on subscription create, later on bd it appears with base plan price on order items table.

**Comment by sandervanhooft** [comment]
Hi @sha1md5 ,

Preprocessors are currently not supported on first payments. Easiest workaround is to first obtain a mandate through a one-off charge, then start the subscription.
