### ISSUE TITLE
Payment property is not working on order, but is referenced in PHPDoc

### ISSUE THREAD

**Issue by jordysinke** [mollie/laravel-cashier-mollie#65]
https://github.com/mollie/laravel-cashier-mollie/blob/6842dd2b98de3b7b56e4a4030794d40e7924115a/src/Order/Order.php#L48

**Comment by sandervanhooft** [comment]
Seems like you're correct @jordysinke !

@ciungulete can you remove the property reference here?

**Comment by ciungulete** [comment]
https://github.com/mollie/laravel-cashier-mollie/pull/69

**Comment by ciungulete** [comment]
Can u check it [here](https://github.com/mollie/laravel-cashier-mollie/pull/69)
