### ISSUE TITLE
Cannot create orders for one time payments.

### ISSUE THREAD

**Issue by Furqan311** [mollie/laravel-cashier-mollie#67]
Hi there,
I have newly started integrating cashiermollie in Laravel. As a newbie, i was a bit confused. But Laravel CashierStripe does a lot of help in understanding how things work.

The problem is aroused when integrating the onetime payment, as the payment from the mollie is successful. But cashierollie is just creating an entry inside the payments table. But the documentation says that when you run the `php artisan cashier:run` command it will create an order. But it is not creating.

I just want to make sure that if this is a bug or single-time payments just need to be manually marked as paid from the webhook.
Thanks in advance and stay blessed.

**Comment by sandervanhooft** [comment]
Hi @Furqan311 ,

An Order is created once the payment gets paid.

If you need more assistance, can you provide a code sample to reproduce the issue, and describe the behavior you're seeing in Mollie's dashboard?

**Comment by Furqan311** [comment]
Thank you for replying,

The code is: 
````
$billableModel = $offer->getDeal->type ? $offer->getDeal->getCompany : $offer->getDeal->getCustomer;
        $item = new ChargeItemBuilder($billableModel);
        $item->unitPrice(money(1000, 'EUR')); //1 EUR
        $item->description('Test Item 1');
        $chargeItem = $item->make();

        $result = $billableModel->newCharge()
        ->addItem($chargeItem)
        ->create();
````

And inside the mollie dashboard, i am getting paid payments. But cashier is not doing anything when I run `cashier:run`, it says 0 Orders created.

![Screenshot from 2022-03-09 15-00-56](https://user-images.githubusercontent.com/22428696/157418857-9b06ce88-ab56-489f-a512-43e2897123e7.png)

The screenshot i attached is from mollie dashboard.

**Comment by sandervanhooft** [comment]
Hi @Furqan311 ,

Thanks for following up.

Once the payment  at Mollie reaches status `paid`, Mollie calls your Cashier webhook url. Cashier then processes the Charge into an Order.

The Mollie dashboard currently shows on the right side of the screen that Mollie cannot reach your webhook (status 404).

**Comment by Furqan311** [comment]
Yes you are right, the reason is i am working on localhost. But then i simulates a manual request via curl To check if the webhook being called. But nothing works.

I am using controller from Cashier's WebhookController, but same issue.

**Comment by sandervanhooft** [comment]
1. When testing, are you pointing your browser to the ngrok generated url?
2. Did you update APP_URL in your env file to the gnrok generated url?

**Comment by sandervanhooft** [comment]
Can you check your Laravel logs?

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
