### ISSUE TITLE
Wrong amount inserted in refunds

### ISSUE THREAD

**Issue by JelleVanDerMeulen** [mollie/laravel-cashier-mollie#7]
Debug shows that the amount inserted in the refund table is written as a string (ex: "18.15"). This result in is a wrong amount of 18 where it should be 1815.

**Comment by sandervanhooft** [comment]
Hi @JelleVanDerMeulen !

Can you share some code so we can reproduce the issue?

**Comment by JelleVanDerMeulen** [comment]
// first we create a subscription
$result = $eenheid->newSubscription($name, $plan)
                ->quantity(10)
                ->create();
// payment is inserted with amount as integer value
insert into `payments` (`mollie_payment_id`, `mollie_payment_status`, `owner_type`, `owner_id`, `currency`, `amount`, `amount_refunded`, `amount_charged_back`, `mollie_mandate_id`, `first_payment_actions`, `updated_at`, `created_at`) values ('tr_yTMqJBGBrT', 'open', 'App\Models\Eenheid', 81, 'EUR', **1815**, 0, 0, '', '[{\"handler\":\"Laravel\\Cashier\\FirstPayment\\Actions\\StartSubscription\",\"description\":\"Maandelijkse betaling standaard-licentie\",\"subtotal\":{\"currency\":\"EUR\",\"value\":\"15.00\"},\"taxPercentage\":21,\"plan\":\"standaard_maand\",\"name\":\"Uw lidmaatschap\",\"quantity\":10}]', '2021-11-23 09:17:04', '2021-11-23 09:17:04')

// mollie webhook insters the subscription correctly


// Here we start the refund
$order = Order::find($order_id);
$order->refundCompletely();

// debugbar shows insert statement in refund table with total as a string. Only 18 will appear in the database
insert into `refunds` (`owner_type`, `owner_id`, `original_order_id`, `total`, `currency`, `mollie_refund_id`, `mollie_refund_status`, `updated_at`, `created_at`) values ('App\Models\Eenheid', 81, 46, **'18.15'**, 'EUR', 're_aqEnaS9rvp', 'pending', '2021-11-23 09:17:21', '2021-11-23 09:17:21')

**Comment by ciungulete** [comment]
Hi @JelleVanDerMeulen,

Solved after #13  will be merged

**Comment by sandervanhooft** [comment]
Thanks guys!

Released here: https://github.com/mollie/laravel-cashier-mollie/releases/tag/v2.0.1
