### ISSUE TITLE
Empty mandate

### ISSUE THREAD

**Issue by turpoint** [mollie/laravel-cashier-mollie#70]
After a successful payment, the mollie_customer_id gets filled in, but mollie_mandate_id is empty. Did anyone have this issue already? There have been 6 other first payments where the mollie_mandate_id is correctly set. It has been paid with the Belfius Pay Button.

In the logs I see a "Laravel\Cashier\Exceptions\InvalidMandateException: Invalid customer mandate" was thrown. I've fetched details about the specific mandate via a manual API call, and the status is "pending". Does that have something to do with it?

**Comment by turpoint** [comment]
FYI: It looks like this happens every time with the Belfius Pay Button.

**Comment by ciungulete** [comment]
https://github.com/mollie/laravel-cashier-mollie/pull/94

**Comment by sandervanhooft** [comment]
Solved and released!

**Comment by sandervanhooft** [comment]
Thanks @ciungulete !
