### ISSUE TITLE
How to get only the redirect URL so it is usable in SPA?

### ISSUE THREAD

**Issue by ixperiencenl** [mollie/laravel-cashier-mollie#71]
Thanks for this wonderful package. I was wondering if it is possible to return only the redirect URL to Mollie after a first payment made, instead of a RedirectToCheckoutResponse which also includes a full HTML code.

This, because I am using a Vue frontend and I want to put a redirect message before sending customer 'abroad'.

Thanks a lot.

**Comment by ixperiencenl** [comment]
Perfect, just tested and it works. thanks Sander! I couldn't find this in the documentation however (although it's in the code of course). Maybe handy to add.

**Comment by sandervanhooft** [comment]
Good thinking! I've added a ticket to remind me here: #72
