### ISSUE TITLE
Payment paid handling and canceled subscription not working correctly

### ISSUE THREAD

**Issue by FutyWidget** [mollie/laravel-cashier-mollie#74]
**Situation:**
User has an active subscription. For this, a payment is made in Mollie. It takes a few days for Mollie to process this payment. In the meantime, the user cancels his subscription. The ends_at date is filled in with the end date of the current cycle. The user has an active subscription until the ends_at date. Now Mollie has successfully processed the deposited payment and the webhook is called. This sets the ends_at date of the subscription to null. This means that the subscription is no longer terminated. In addition, the cycle_ends_at date is also empty and no new OrderItem has been scheduled.

In the previous version of the package(v1) we didn't have this problem. I have investigated where the problem originated. In the previous version, the handlePaymentPaid method on the Subscription model was empty:
```
/**
 * Handle a paid payment.
 *
 * @param \Laravel\Cashier\Order\OrderItem $item
 * @return void
 */
public static function handlePaymentPaid(OrderItem $item)
{
    // Subscriptions are prolonged optimistically (so before payment is being completely processed).
}
```

The following lines have been added in the current version by @ciungulete. What causes the problem:
```
/**
 * Handle a paid payment.
 *
 * @param \Laravel\Cashier\Order\OrderItem $item
 * @return void
 */
public static function handlePaymentPaid(OrderItem $item)
{
    $subscription = $item->orderable;

    if ($subscription->ends_at !== null) {
        $subscription->update([
            'ends_at' => null,
        ]);
    }
}
```
Why was this added? Then I might be able to help you find a solution to the problem.

Thanks in advance!

**Comment by sandervanhooft** [comment]
Hi @FutyWidget,

Thanks for reporting this! This was introduced along with the retry feature:

- on the first attempt, if it fails, the subscription gets canceled.
- when triggering a retry, the subscription gets restored if the payment succeeds.
