### ISSUE TITLE
Allow to change payment status of payment

### ISSUE THREAD

**Issue by b0wdyy** [mollie/laravel-cashier-mollie#76]
I'm trying to test recurring payments. I don't see any methods/functions to help me with it. In the [mollie docs ](https://docs.mollie.com/overview/testing) there is documentation on how to do it. _...Instead, a changePaymentState URL is added, which allows you to set the final payment state for these payments._ 

Is there any implementation of it in this package? Would be nice to see you guys help me out.

Thanks for this amazing package!

**Comment by sandervanhooft** [comment]
If you have a Cashier Payment model you can obtain the original Mollie Payment object' links like this:

```php
$payment->asMolliePayment()->_links;
```

If I remember correctly there is also a helper method on the Mollie Payment object to retrieve the url you're looking for.

Hope that helps, enjoy!
