### ISSUE TITLE
First time payment charges the plan amount instead of first payment amount

### ISSUE THREAD

**Issue by ixperiencenl** [mollie/laravel-cashier-mollie#78]
hi guys,

thanks for this wonderful package. Works almost fine on my project.

I am having an issue regarding the first payment.

I am using a custom model for the Plan, as described in your documentation. My Plan model is as follows:

`<?php

namespace App\Models;

use Laravel\Cashier\Plan\Plan as CashierPlan;
use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'amount' => 'array',
        'first_payment_amount' => 'array',
        'first_payment_method' => 'array',
        'meta' => 'array',
    ];
    /**
     * Builds a Cashier plan from the current model.
     *
     * @returns \Laravel\Cashier\Plan\Plan
     */
    public function buildCashierPlan(): CashierPlan
    {
        $plan = new CashierPlan($this->name);
        
        return $plan->setAmount(mollie_array_to_money($this->amount))
            ->setInterval($this->interval)
            ->setDescription($this->description)
            ->setFirstPaymentMethod($this->first_payment_method)
            ->setFirstPaymentAmount(mollie_array_to_money($this->first_payment_amount))
            ->setFirstPaymentDescription($this->first_payment_description)
            ->setFirstPaymentRedirectUrl($this->first_payment_redirect_url)
            ->setFirstPaymentWebhookUrl($this->first_payment_webhook_url);
    }
}`

My database table looks like this:
INSERT INTO `plans` (`id`, `name`, `group`, `description`, `amount`, `interval`, `meta`, `first_payment_method`, `first_payment_amount`, `first_payment_description`, `first_payment_webhook_url`, `first_payment_redirect_url`, `created_at`, `updated_at`) VALUES (1, 'one-month', 'basic', 'Monthly Subscription', '{"value":"50.00","currency":"EUR"}', '1', '{"start_price":"40.00"}', '[]', '{"value":"5.00","currency":"EUR"}', 'Basic 1 Month', 'irrelevant', 'irrelevant', '2022-03-10 16:24:35', '2022-03-10 16:24:36');

Somehow, when a customer makes a first payment (without a mandate), it charges EUR 50 instead of 5. How come? I also defined the plans in my Service Provider:
`
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(\Laravel\Cashier\Plan\Contracts\PlanRepository::class, DatabasePlanRepository::class);
    }`

I hope someone can help. I guess it's just someting overlooked but don't know...
Thank you very much.

**Comment by sandervanhooft** [comment]
This is by design. The first-payment-amount is only used to determine the minimum amount to use when obtaining a mandate. Typically when you start the subscription with a trial period.

If the subscription is started normally, it just charges the normal subscription amount.

**Comment by ixperiencenl** [comment]
I understand this. 
But then what I don't understand is that when the queue is run, it makes a new payment right after the first one. 
So my customer pays 2 times EUR 75 instead of one time for the first month.
How come?

**Comment by sandervanhooft** [comment]
Can you share an example set of db records to illustrate this?

**Comment by ixperiencenl** [comment]
Yes. 
I have just made a test payment with a new account (and new email address). 
It creates a new db Order row:
![image](https://user-images.githubusercontent.com/9009015/163999684-8781f547-5073-45a4-b62d-bd44ff76a512.png)
Which is fine of course.

Now I run `php artisan cashier:run` and it says `Created 1 orders` - it created another record in Orders:
![image](https://user-images.githubusercontent.com/9009015/163999744-650acfd0-fa36-4e98-be0a-2da4270bc8bf.png)

In Mollie I see these orders, from one is iDeal (which was the first payment method) and another one is SEPA (which is fine, but not right after the first payment, should be recurring in a month)
![image](https://user-images.githubusercontent.com/9009015/164000016-3166ff43-b038-4883-b4d4-183ce33bccd7.png)

In my **Plans** table, I use **1** as interval, and not **1 month** - can this be the issue?

**Comment by sandervanhooft** [comment]
That could indeed be the issue
