### ISSUE TITLE
Reimburse cost of previous plan when changing to different plan within a few minutes gives 0 reimbursement

### ISSUE THREAD

**Issue by bertpareyn** [mollie/laravel-cashier-mollie#80]
Scenario: Subscribe to Plan A for 10 euro and change to Plan B for 20 euro within a few minutes

Expected outcome: Plan B is started and the user is charged 10 euros (Plan B 20 euro - Plan A 10 euro === 10 euro to upgrade to Plan B)

Actual outcome: Plan B is started and the user is charged 20 euros (No reimbursement for Plan A given)

What we think the issue is: 

Consider the following code https://github.com/mollie/laravel-cashier-mollie/blob/main/src/Subscription.php#L747 
```php
        if (round($this->getCycleLeftAttribute($now), 3) == 1) {
            return null;
        }
```
We assume the check is there to make sure that on the last day of the plan you don't get reimbursed a couple of cents but this is actually checking on the first day and so it does the inverse and not give any reimbursement on the first day. This causes people to not be able to change plans and get reimbursed for the old plan that was just started.

We think there might be a bug in the `if` check and the code should be
```php
        if (round($this->getCycleLeftAttribute($now), 3) == 0) {
            return null;
        }
```
This would then always reimburse the user for a plan that was started. It's also unclear as to why the precision is 3 instead of the default 5 in the function.

Are we interpreting this logic correctly?

**Comment by ciungulete** [comment]
https://github.com/mollie/laravel-cashier-mollie/pull/98
