### ISSUE TITLE
Variable first payment amount

### ISSUE THREAD

**Issue by turpoint** [mollie/laravel-cashier-mollie#82]
Is there a way we could change the first payment amount when we start a subscription with a trial (mandate upfront)?

I know there were some open issues about this in the V1 repo, but I couldn't really find any documentation about this, or an example on how to use the `FirstPaymentBuilder` manually.

**Comment by sandervanhooft** [comment]
Hi!

Let me try to understand your use case. With `mandate upfront`, do you mean you already have a mandate for the billable model?

**Comment by turpoint** [comment]
Hi :)

No, not really. I was referencing the [documentation](https://www.cashiermollie.com/03-trials.html#with-mandate-upfront).

It's the first payment (that starts the trial) that we would want to be variable.

**Comment by sandervanhooft** [comment]
It's possible to override the first payment amount per plan in the plan config. Would that help you?

**Comment by turpoint** [comment]
@sandervanhooft Thank you, for this use case the first payment per plan in the config worked fine :) I've just created a couple of extra plans.

**Comment by sandervanhooft** [comment]
Great, enjoy!
