### ISSUE TITLE
Method Laravel\Cashier\Order\OrderItemCollection::getCurrency does not exist.

### ISSUE THREAD

**Issue by tobischulz** [mollie/laravel-cashier-mollie#84]
# Problem

Swapping plan on active subscription which used a coupon on subscription create, the restartCycleModifications reimbuseUnusedTime calls a not existing method `getCurrency` on the `OrderItemCollection`. With this exception the customer is unable to ever change his subscription.

# How to reproduce
A customer has subscribed with a coupon. The customer decides to swap his plan. 

- create subscription with coupon
- get the subscription
- call swap method with different plan
- exception occures

# Related code

The chain of method calls from the Subscription model swap method is:

- [swap](https://github.com/mollie/laravel-cashier-mollie/blob/050c6dac3cfb36c478cddb0499ca90fc9d6d4d69/src/Subscription.php#L200)
- [restartCycleWithModifications](https://github.com/mollie/laravel-cashier-mollie/blob/050c6dac3cfb36c478cddb0499ca90fc9d6d4d69/src/Subscription.php#L770)
- [reimburseUnusedTime](https://github.com/mollie/laravel-cashier-mollie/blob/050c6dac3cfb36c478cddb0499ca90fc9d6d4d69/src/Subscription.php#L739)
- [reimbursableAmount](https://github.com/mollie/laravel-cashier-mollie/blob/050c6dac3cfb36c478cddb0499ca90fc9d6d4d69/src/Subscription.php#L688)
- [$appliedCouponOrderItems->getTotal()](https://github.com/mollie/laravel-cashier-mollie/blob/050c6dac3cfb36c478cddb0499ca90fc9d6d4d69/src/Subscription.php#L723)

The getTotal method on [OrderItemCollection](https://github.com/mollie/laravel-cashier-mollie/blob/main/src/Order/OrderItemCollection.php#L157) want to call the getCurrency method which does not exist. 

![CleanShot 2022-05-05 at 12 15 13](https://user-images.githubusercontent.com/576014/166903965-1f16c228-9a25-4dc3-8554-9eb5237d2d19.jpg)

# Possible solution

As it is a collection of OrderItems it should get the currency from the OrderItems. Additional the `total` does not exist in OrderItem. Maybe here is `unit_price` the correct field. Here is a possible solution to that. 

 Laravel\Cashier\Order\OrderItemCollection.php

![CleanShot 2022-05-05 at 12 15 46](https://user-images.githubusercontent.com/576014/166904055-25e1b280-69b5-463b-8b45-7d40b58ea2ff.jpg)

I hope i got this right and it helps to fix this as we are currently in this situation that our customer cant swap his subscription. 

Thanks and Regards

**Comment by sandervanhooft** [comment]
Thanks for the extensive report @tobischulz ! Working on a patch right away.

Note that the `total` field does exist as a dynamic attribute (on `OrderItem`)

**Comment by sandervanhooft** [comment]
All good now. https://github.com/mollie/laravel-cashier-mollie/releases/tag/v2.3.3

Thanks @tobischulz !

**Comment by tobischulz** [comment]
Thank you @sandervanhooft !! 🫶
