### ISSUE TITLE
Missing cycle duration for a new subscription in an invoice

### ISSUE THREAD

**Issue by KumaVolt** [mollie/laravel-cashier-mollie#87]
Creating a new subscription results in an invoice without the cycle being noted.  

Debugging the code i found that it runs createProcessedFromItems function which runs the $process_items always set at false, (src/Order/Order.php at line 151) . Hence the reason why description_extra_lines for order_item is never set and why the cycle is missing from the invoice.

**Comment by ciungulete** [comment]
Solved here https://github.com/mollie/laravel-cashier-mollie/pull/99

**Comment by ciungulete** [comment]
This can be closed, it's solved.

**Comment by sandervanhooft** [comment]
Thanks @ciungulete !
