### ISSUE TITLE
Payment via newSubscriptionViaMollieCheckout when registering through Fortify

### ISSUE THREAD

**Issue by Joezoefhalihoza** [mollie/laravel-cashier-mollie#88]
In our application we want to redirect to Mollie to create an subscription after the user has redirected. When using the  ``` Features::emailVerification() ``` option from Fortify the request needs to implement the interface Authenticatable, but when redirecting to Mollie it creates a RedirectToCheckoutResponse resulting in the following error.
``` Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, instance of Laravel\Cashier\SubscriptionBuilder\RedirectToCheckoutResponse given, called in /var/www/html/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php on line 56  ``` 
Is there any way around this except disabling the emailVerification?

**Comment by sandervanhooft** [comment]
Hi @Joezoefhalihoza ,

Can you share some example code to reproduce this issue?

**Comment by Joezoefhalihoza** [comment]
@sandervanhooft 
```
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Laravel\Fortify\Contracts\CreatesNewUsers;
use Laravel\Jetstream\Jetstream;

class CreateNewUser implements CreatesNewUsers {
use PasswordValidationRules;

public function create(array $input)
{
    Validator::make($input, [
        'name' => ['required', 'string', 'max:255'],
        'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
        'password' => $this->passwordRules(),
        'subscription' => ['string', 'nullable', 'max:15'],
        'terms' => Jetstream::hasTermsAndPrivacyPolicyFeature() ? ['required', 'accepted'] : '',
    ])->validate();

    $user =  User::create([
        'name' => $input['name'],
        'email' => $input['email'],
        'password' => Hash::make($input['password']),
        'subscription' => $input['subscription'],
    ]);

    return $user->newSubscription('main', $input['subscription'])
        ->trialDays(30)
        ->create();

        //return $user; this is the standard action that contains the authenticable object.
}
}
