### ISSUE TITLE
When amount to pay exceeds payment method max allowed amount the Order fails silently

### ISSUE THREAD

**Issue by bertpareyn** [mollie/laravel-cashier-mollie#91]
Variable: The payment method limit. e.g., Credit Cards default to a 2k limit.

Scenario:
- Start and pay for a new subscription for a total charged amount that is less than the limit e.g. 100 euros.
- Adjust the subscription so that the total charged amount for the next cycle will be more than the allowed amount for the payment method. e.g., 2.5k on the credit card with a limit of 2k.
- Finish the billing cycle

What happens:
- Notice that when the billing cycle ends the order for 2.5k is created and an attempt is made to charge the CC.
- An error is returned from the Mollie API [for this call](https://github.com/mollie/laravel-cashier-mollie/blob/main/src/Order/Order.php#L230):
```
Error executing API call (422: Unprocessable Entity): The amount is higher than the maximum. Field: amount. Documentation: https://docs.mollie.com/overview/handling-errors
```
- This stops order processing in its tracks and does not throw any events which would make it possible to identify the failed payment. Next to that, the order stays marked with a temporary payment ID e.g., `temp_b2eeb17a-d886-235b-b4da-217dff33ecbd`

How should this case be handled?

**Comment by sandervanhooft** [comment]
Hi @bertpareyn !

Thank you for the detailed report. That's an interesting case, I haven't encountered this one before.

Touching a few points here:

1. the payment maximum limit was hit. I'd advice to contact Mollie support to increase it if that makes sense for your use case. OR consider decreasing the billing interval, thereby practically lowering the amount being charged each time.
2. Cashier should at least throw an exception when an amount beyond the limit is charged, both on first payments and mandated payments. This way it prevents getting into an invalid state.
3. Your orders are / order processing is now in an invalid state, which needs reverting.

Is this correct?

Regarding point 3, can you share the table row for the order, and (if any) the row for the related payment? Ideally with column headers so I know which is what :)

**Comment by ciungulete** [comment]
This can be closed, it's solved.
