### ISSUE TITLE
Bank transfer as payment method

### ISSUE THREAD

**Issue by pecuchet** [mollie/laravel-cashier-mollie#92]
Hello @sandervanhooft and others, quick question: is it possible to use Mollie's bank transfer payment method with the package? And if so, how does it work when the subscription is to be renewed? I see `dueDate` and `billingEmail` properties in `Mollie\Api\Resources\Payment`, but not much else... 

(It doesn't seem possible to test the bank transfer method in Mollie's dev mode.)

**Comment by sandervanhooft** [comment]
Hi @pecuchet

Not sure what you mean but let me try to clear it up.

This package works by obtaining a payment mandate through Mollie's checkout and then schedules/triggers mandated payments when these are due.

Only payment methods eligible for "first payments" can be used in that checkout to obtain the mandate.

Except for creditcard and PayPal, all other eligible payment methods will result in a bank transfer mandate.

Alternatively, you could create that mandate manually using the Mollie API by providing some details such as the SEPA reference. If you store that mandate id along with the customer id on the billable model, this package can handle the remainder of the subscription logic.

**Comment by pecuchet** [comment]
Hi @sandervanhooft, 
Indeed I meant a manual bank transfer, like SEPA, and wondered if it is eligible as a first payment method. If I understand your last paragraph correctly, it's not out of the box with your package. So if I want to support it, I have to implement a custom first payment flow for that method?

**Comment by sandervanhooft** [comment]
You can collect the data using your own form and create the mandate through Mollie's API, without the customer having to go through Mollie's checkout.

Something like:

```php
$mandate = mollie()->mandates->create([
    'customerId' => $billable->mollieCustomerId(),
    // rest of payload
]);

$billable->mollie_mandate_id = $mandate->id;
$billable->save();
```

See https://docs.mollie.com/reference/v2/mandates-api/create-mandate for the actual payload contents and more.

**Comment by pecuchet** [comment]
Ok, thanks @sandervanhooft !

**Comment by sandervanhooft** [comment]
No problem, enjoy!
