### ISSUE TITLE
Recurring payment check

### ISSUE THREAD

**Issue by JessedeB** [mollie/laravel-cashier-mollie#93]
I want to test when a client gets a new order, how the order is being processed with iDeal and if the payment has succeed since the recurring date is set 2 days later. 

Also how is the first time payment amount being processed? There's no data on the order and it's not being calculated within the price.

**Comment by sandervanhooft** [comment]
What have you tried so far?

**Comment by JessedeB** [comment]
Hello, the test has been succeed which was caused due a wrong set listener. Though, i've not succeed in adding an additional order_item to an order ( connection fee ), is there a way to extend the Order class or add an array to the config since the fee is a fixed value so that on the first payment a second rule is applied to the order?

**Comment by sandervanhooft** [comment]
A) Consider using a Charge for the first payment, which allows you to set any order items you like, and will result in a mandate if there is not any. Optionally force the customer through Mollie's checkout to always obtain a new one.

- Or -

B) Look into manually using the FirstPaymentBuilder.
