### ISSUE TITLE
Differentiate actual one-time charges from a mandate update transaction

### ISSUE THREAD

**Issue by byoan** [mollie/laravel-cashier-mollie#97]
Hi,

I'm currently in the process of migrating a project from Cashier Mollie v1 to v2, and I'm having trouble differentiating an actual one-time charge that I create using the `newCharge` method on my Billable model, and a one-time charge that's created by the package when updating a mandate through `updatePaymentMethod`.

The reason I have to differentiate them is because I'm using an event listener with the package's events in order to generate invoices through a 3rd party service.

While I can easily differentiate one-time charges' orders from subscriptions' orders by the absence of an `orderable_type`, I would have imagined an easier solution than to compare the unit price of the order item with the amount in  `config('cashier.update_payment_method.amount.value')` in order to differentiate a mandate update transaction from an actual one-time charge.

Maybe am I missing something?

Thanks in advance

**Comment by byoan** [comment]
Hi @sandervanhooft,

I am talking about v2 (I was just mentioning that I am upgrading an existing project)

I am having this issue using the new one time charges features from v2.

**Comment by sandervanhooft** [comment]
So do I understand correctly that you are looking for a way to distinguish between the following?

1. generated by a one time charge
2. generated by a payment method update

Also, are you trying to distinguish by Event type, or on the Order model, or on the Payment model, or something else? I am trying to get the picture here 😄

**Comment by byoan** [comment]
Yes, I am trying to distinguish both of these cases when handling an event such as an order being paid (as both these cases would trigger the event), so either on the Event or the Order/OrderItem models

Maybe having a dedicated `orderable_type` on the OrderItem that represents a one-time charge? So a mandate update order item would be left with a null value as we did not order anything in particular?
